{{-- Dashboard Calendar Component --}}
<div class="dashboard-calendar-wrapper">
    <div class="dashboard-calendar-shell">
        <div class="dashboard-calendar-header">
            <div>
                <span class="dashboard-calendar-kicker">Academic schedule</span>
                <h2 class="dashboard-calendar-title" id="calendar-month-year">
                    {{-- Month/Year will be set by JavaScript --}}
                </h2>
            </div>

            <div class="dashboard-calendar-controls">
                <button id="calendar-today-btn" class="dashboard-calendar-btn dashboard-calendar-btn-primary" aria-label="Go to today">
                    Today
                </button>
                <button id="calendar-prev-btn" class="dashboard-calendar-btn dashboard-calendar-btn-nav" aria-label="Previous month">
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
                    </svg>
                </button>
                <button id="calendar-next-btn" class="dashboard-calendar-btn dashboard-calendar-btn-nav" aria-label="Next month">
                    <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                    </svg>
                </button>
            </div>
        </div>

        <div class="dashboard-calendar-weekdays" aria-hidden="true">
            <div>Sun</div>
            <div>Mon</div>
            <div>Tue</div>
            <div>Wed</div>
            <div>Thu</div>
            <div>Fri</div>
            <div>Sat</div>
        </div>

        <div class="dashboard-calendar-grid" id="calendar-grid">
            {{-- Days will be generated by JavaScript --}}
        </div>

        <div id="calendar-loading" class="dashboard-calendar-loading hidden">
            <div class="dashboard-calendar-spinner" aria-hidden="true"></div>
            <p>Loading calendar...</p>
        </div>

        <div id="calendar-error" class="dashboard-calendar-error hidden">
            Failed to load calendar. Please refresh the page.
        </div>
    </div>

    <div id="calendar-day-events" class="dashboard-calendar-events hidden">
        <div class="dashboard-calendar-events-panel">
            <h3 class="dashboard-calendar-events-title" id="calendar-events-title">
                {{-- Title will be set by JavaScript --}}
            </h3>
            <div id="calendar-events-list" class="dashboard-calendar-events-list">
                {{-- Events will be populated by JavaScript --}}
            </div>
            <div id="calendar-no-events" class="dashboard-calendar-empty hidden">
                <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                </svg>
                <p>No events scheduled for this day.</p>
            </div>
        </div>
    </div>
</div>

<style>
    .dashboard-calendar-wrapper {
        display: flex;
        flex-direction: column;
        gap: 1.25rem;
        color: var(--text-main);
    }

    .dashboard-calendar-shell {
        background: linear-gradient(180deg, rgba(255,255,255,0.96), rgba(248,250,252,0.96));
        border: 1px solid var(--border-color);
        border-radius: var(--radius-xl);
        box-shadow: var(--shadow-card);
        padding: 1.25rem;
    }

    .dashboard-calendar-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 1rem;
        margin-bottom: 1.25rem;
        padding-bottom: 1rem;
        border-bottom: 1px solid var(--border-color);
    }

    .dashboard-calendar-kicker {
        display: inline-block;
        margin-bottom: 0.4rem;
        font-size: 0.7rem;
        font-weight: 800;
        letter-spacing: 0.14em;
        text-transform: uppercase;
        color: var(--crimson-700);
    }

    .dashboard-calendar-title {
        margin: 0;
        font-size: clamp(1.25rem, 2vw, 1.75rem);
        font-weight: 800;
        letter-spacing: -0.03em;
        color: var(--navy-900);
    }

    .dashboard-calendar-controls {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        flex-wrap: wrap;
    }

    .dashboard-calendar-btn {
        border: 1px solid var(--border-color);
        background: var(--bg-surface);
        color: var(--navy-700);
        border-radius: var(--radius-md);
        min-height: 38px;
        cursor: pointer;
        transition: all var(--transition-speed);
    }

    .dashboard-calendar-btn:hover {
        background: var(--bg-primary);
        border-color: var(--navy-600);
        color: var(--navy-800);
    }

    .dashboard-calendar-btn:focus-visible {
        outline: 2px solid var(--navy-600);
        outline-offset: 2px;
    }

    .dashboard-calendar-btn-primary {
        padding: 0.5rem 0.9rem;
        font-size: 0.8rem;
        font-weight: 700;
        background: rgba(15, 118, 110, 0.08);
        border-color: rgba(15, 118, 110, 0.22);
        color: var(--navy-800);
    }

    .dashboard-calendar-btn-primary:hover {
        background: rgba(15, 118, 110, 0.12);
    }

    .dashboard-calendar-btn-nav {
        width: 38px;
        height: 38px;
        display: flex;
        align-items: center;
        justify-content: center;
    }

    .dashboard-calendar-btn-nav svg {
        width: 18px;
        height: 18px;
    }

    .dashboard-calendar-weekdays,
    .dashboard-calendar-grid {
        display: grid;
        grid-template-columns: repeat(7, minmax(0, 1fr));
        gap: 0.55rem;
    }

    .dashboard-calendar-weekdays {
        margin-bottom: 0.7rem;
    }

    .dashboard-calendar-weekdays div {
        text-align: center;
        font-size: 0.72rem;
        font-weight: 700;
        letter-spacing: 0.06em;
        text-transform: uppercase;
        color: var(--text-muted);
        padding: 0.4rem 0.25rem;
    }

    .dashboard-calendar-grid {
        min-height: 360px;
    }

    .calendar-day {
        display: flex;
        flex-direction: column;
        min-height: 96px;
        padding: 0.55rem 0.45rem;
        border: 1px solid var(--border-color);
        border-radius: var(--radius-md);
        background: rgba(255,255,255,0.82);
        cursor: pointer;
        transition: all var(--transition-speed);
    }

    .calendar-day:hover {
        transform: translateY(-1px);
        border-color: rgba(15, 118, 110, 0.35);
        background: rgba(240, 253, 250, 0.8);
        box-shadow: 0 8px 18px rgba(15, 23, 42, 0.06);
    }

    .calendar-day.disabled {
        background: rgba(148, 163, 184, 0.05);
        color: rgba(100, 116, 139, 0.7);
        cursor: default;
    }

    .calendar-day.disabled:hover {
        transform: none;
        border-color: var(--border-color);
        background: rgba(148, 163, 184, 0.05);
        box-shadow: none;
    }

    .calendar-day.today {
        border-color: rgba(15, 118, 110, 0.7);
        background: linear-gradient(180deg, rgba(15, 118, 110, 0.08), rgba(255,255,255,0.9));
    }

    .calendar-day.is-selected {
        border-color: rgba(113, 35, 54, 0.72);
        background: rgba(254, 242, 242, 0.9);
    }

    .calendar-day-number {
        display: flex;
        align-items: center;
        justify-content: center;
        width: 28px;
        height: 28px;
        margin-bottom: 0.4rem;
        border-radius: 50%;
        font-size: 0.8rem;
        font-weight: 700;
        color: var(--navy-800);
    }

    .calendar-day.today .calendar-day-number {
        background: var(--navy-800);
        color: #fff;
    }

    .calendar-day.disabled .calendar-day-number {
        color: rgba(100, 116, 139, 0.7);
        background: transparent;
    }

    .calendar-events {
        display: flex;
        flex-direction: column;
        gap: 0.2rem;
        overflow: hidden;
    }

    .calendar-event-dot {
        display: inline-block;
        width: 7px;
        height: 7px;
        margin-right: 0.4rem;
        border-radius: 50%;
        vertical-align: middle;
    }

    .calendar-event-label {
        display: flex;
        align-items: center;
        font-size: 0.64rem;
        line-height: 1.3;
        color: var(--navy-700);
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .dashboard-calendar-loading,
    .dashboard-calendar-error {
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 0.75rem;
        min-height: 90px;
        color: var(--text-muted);
        font-size: 0.9rem;
        margin-top: 0.5rem;
    }

    .dashboard-calendar-error {
        color: #b4232f;
        background: rgba(190, 24, 93, 0.04);
        border: 1px solid rgba(190, 24, 93, 0.18);
        border-radius: var(--radius-md);
        padding: 0.85rem 1rem;
    }

    .dashboard-calendar-spinner {
        width: 24px;
        height: 24px;
        border: 2px solid rgba(15, 118, 110, 0.2);
        border-top-color: rgba(15, 118, 110, 0.9);
        border-radius: 50%;
        animation: dashboard-spin 0.8s linear infinite;
    }

    @keyframes dashboard-spin {
        to { transform: rotate(360deg); }
    }

    .dashboard-calendar-events {
        display: block;
    }

    .dashboard-calendar-events-panel {
        background: linear-gradient(180deg, rgba(255,255,255,0.96), #ffffff);
        border: 1px solid var(--border-color);
        border-radius: var(--radius-xl);
        box-shadow: var(--shadow-card);
        padding: 1.25rem;
    }

    .dashboard-calendar-events-title {
        margin: 0 0 1rem;
        font-size: 1.05rem;
        font-weight: 800;
        color: var(--navy-900);
    }

    .dashboard-calendar-events-list {
        display: flex;
        flex-direction: column;
        gap: 0.85rem;
    }

    .calendar-event-item {
        border-left: 4px solid var(--navy-600);
        background: linear-gradient(135deg, rgba(248,250,252,0.9), rgba(255,255,255,0.95));
        border-radius: 0 var(--radius-md) var(--radius-md) 0;
        padding: 0.9rem 1rem;
    }

    .calendar-event-item-title {
        margin: 0 0 0.4rem;
        font-size: 0.95rem;
        font-weight: 700;
        color: var(--navy-900);
    }

    .calendar-event-item-meta {
        margin: 0;
        font-size: 0.8rem;
        color: var(--text-muted);
        line-height: 1.6;
    }

    .dashboard-calendar-empty {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap: 0.6rem;
        min-height: 140px;
        color: var(--text-muted);
        text-align: center;
    }

    .dashboard-calendar-empty svg {
        width: 40px;
        height: 40px;
        color: rgba(148, 163, 184, 0.8);
    }

    .dashboard-calendar-empty p {
        margin: 0;
        font-size: 0.9rem;
    }

    .hidden {
        display: none !important;
    }

    @media (max-width: 767.98px) {
        .dashboard-calendar-shell,
        .dashboard-calendar-events-panel {
            padding: 1rem;
        }

        .dashboard-calendar-header {
            flex-direction: column;
            align-items: flex-start;
        }

        .dashboard-calendar-controls {
            width: 100%;
        }

        .dashboard-calendar-btn-primary {
            flex: 1 1 auto;
        }

        .calendar-day {
            min-height: 82px;
            padding: 0.4rem 0.35rem;
        }
    }

    @media (max-width: 480px) {
        .dashboard-calendar-weekdays div {
            font-size: 0.62rem;
            letter-spacing: 0.04em;
        }

        .calendar-day {
            min-height: 68px;
            padding: 0.35rem 0.28rem;
        }

        .calendar-day-number {
            width: 22px;
            height: 22px;
            font-size: 0.72rem;
        }

        .calendar-event-label {
            font-size: 0.58rem;
        }
    }
</style>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const todayBtn = document.getElementById('calendar-today-btn');
        const prevBtn = document.getElementById('calendar-prev-btn');
        const nextBtn = document.getElementById('calendar-next-btn');
        const monthYearEl = document.getElementById('calendar-month-year');
        const calendarGrid = document.getElementById('calendar-grid');
        const loadingEl = document.getElementById('calendar-loading');
        const errorEl = document.getElementById('calendar-error');
        const dayEventsContainer = document.getElementById('calendar-day-events');
        const eventsTitle = document.getElementById('calendar-events-title');
        const eventsList = document.getElementById('calendar-events-list');
        const noEventsEl = document.getElementById('calendar-no-events');

        if (!todayBtn || !prevBtn || !nextBtn || !monthYearEl || !calendarGrid || !loadingEl || !errorEl || !dayEventsContainer || !eventsTitle || !eventsList || !noEventsEl) {
            return;
        }

        let currentDate = new Date();
        let allEvents = {};
        let selectedDay = null;

        const eventColors = {
            class: '#0d3f38',
            exam: '#dc2626',
            assignment: '#f59e0b',
            live: '#1a5c54',
            fee: '#8b5cf6',
            event: '#06b6d4',
            notice: '#6366f1'
        };

        async function initCalendar() {
            await fetchEvents();
            renderCalendar();
        }

        async function fetchEvents() {
            try {
                loadingEl.classList.remove('hidden');
                errorEl.classList.add('hidden');

                const year = currentDate.getFullYear();
                const month = currentDate.getMonth() + 1;
                const response = await fetch(`{{ route('calendar.events') }}?year=${year}&month=${month}`);
                const data = await response.json();

                allEvents = {};
                (data.events || []).forEach((event) => {
                    const startDate = new Date(event.start);
                    const dateStr = startDate.toISOString().split('T')[0];

                    if (!allEvents[dateStr]) {
                        allEvents[dateStr] = [];
                    }

                    allEvents[dateStr].push(event);
                });

                loadingEl.classList.add('hidden');
            } catch (error) {
                console.error('Error fetching events:', error);
                loadingEl.classList.add('hidden');
                errorEl.classList.remove('hidden');
            }
        }

        function renderCalendar() {
            const year = currentDate.getFullYear();
            const month = currentDate.getMonth();

            monthYearEl.textContent = new Date(year, month, 1).toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
            calendarGrid.innerHTML = '';

            const firstDay = new Date(year, month, 1).getDay();
            const daysInMonth = new Date(year, month + 1, 0).getDate();
            const daysInPrevMonth = new Date(year, month, 0).getDate();
            const today = new Date();
            const isCurrentMonth = today.getFullYear() === year && today.getMonth() === month;
            const todayDate = isCurrentMonth ? today.getDate() : null;

            for (let i = firstDay - 1; i >= 0; i--) {
                calendarGrid.appendChild(createDayElement(daysInPrevMonth - i, true));
            }

            for (let day = 1; day <= daysInMonth; day++) {
                const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
                const isToday = isCurrentMonth && day === todayDate;
                const hasEvents = !!(allEvents[dateStr] && allEvents[dateStr].length > 0);
                calendarGrid.appendChild(createDayElement(day, false, isToday, hasEvents, dateStr));
            }

            const totalCells = calendarGrid.children.length;
            const remainingCells = 42 - totalCells;
            for (let day = 1; day <= remainingCells; day++) {
                calendarGrid.appendChild(createDayElement(day, true));
            }
        }

        function createDayElement(day, disabled = false, isToday = false, hasEvents = false, dateStr = null) {
            const el = document.createElement('div');
            el.className = 'calendar-day';
            el.setAttribute('data-date', dateStr || '');

            if (disabled) {
                el.classList.add('disabled');
            }

            if (isToday) {
                el.classList.add('today');
            }

            if (selectedDay && dateStr === selectedDay) {
                el.classList.add('is-selected');
            }

            const dayNumberEl = document.createElement('div');
            dayNumberEl.className = 'calendar-day-number';
            dayNumberEl.textContent = day;
            el.appendChild(dayNumberEl);

            if (hasEvents && !disabled) {
                const eventsEl = document.createElement('div');
                eventsEl.className = 'calendar-events';

                const events = allEvents[dateStr];
                const uniqueTypes = [...new Set(events.map((event) => event.type))];

                uniqueTypes.slice(0, 2).forEach((type) => {
                    const eventEl = document.createElement('div');
                    eventEl.className = 'calendar-event-label';
                    const color = eventColors[type] || '#64748b';
                    eventEl.innerHTML = `<span class="calendar-event-dot" style="background-color: ${color}"></span>${type}`;
                    eventsEl.appendChild(eventEl);
                });

                if (uniqueTypes.length > 2) {
                    const moreEl = document.createElement('div');
                    moreEl.className = 'calendar-event-label';
                    moreEl.textContent = `+${uniqueTypes.length - 2} more`;
                    eventsEl.appendChild(moreEl);
                }

                el.appendChild(eventsEl);
            }

            if (!disabled) {
                el.setAttribute('role', 'button');
                el.setAttribute('tabindex', '0');
                el.addEventListener('click', () => selectDay(dateStr));
                el.addEventListener('keydown', (event) => {
                    if (event.key === 'Enter' || event.key === ' ') {
                        event.preventDefault();
                        selectDay(dateStr);
                    }
                });
            }

            return el;
        }

        function selectDay(dateStr) {
            selectedDay = dateStr;
            const date = new Date(dateStr + 'T00:00:00');
            const dayName = date.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });
            eventsTitle.textContent = dayName;

            const dayEvents = allEvents[dateStr] || [];

            if (dayEvents.length === 0) {
                eventsList.innerHTML = '';
                noEventsEl.classList.remove('hidden');
            } else {
                noEventsEl.classList.add('hidden');
                eventsList.innerHTML = dayEvents.map((event) => `
                    <div class="calendar-event-item" style="border-color: ${eventColors[event.type] || '#64748b'}">
                        <h4 class="calendar-event-item-title">${escapeHtml(event.title)}</h4>
                        <p class="calendar-event-item-meta">Type: <span class="capitalize">${event.type}</span></p>
                        ${event.start ? `<p class="calendar-event-item-meta">Time: ${formatTime(event.start)}</p>` : ''}
                        ${event.end && event.type !== 'assignment' ? `<p class="calendar-event-item-meta">End: ${formatTime(event.end)}</p>` : ''}
                    </div>
                `).join('');
            }

            dayEventsContainer.classList.remove('hidden');
            renderCalendar();
        }

        todayBtn.addEventListener('click', () => {
            currentDate = new Date();
            selectedDay = null;
            dayEventsContainer.classList.add('hidden');
            fetchEvents().then(() => renderCalendar());
        });

        prevBtn.addEventListener('click', () => {
            currentDate.setMonth(currentDate.getMonth() - 1);
            selectedDay = null;
            dayEventsContainer.classList.add('hidden');
            fetchEvents().then(() => renderCalendar());
        });

        nextBtn.addEventListener('click', () => {
            currentDate.setMonth(currentDate.getMonth() + 1);
            selectedDay = null;
            dayEventsContainer.classList.add('hidden');
            fetchEvents().then(() => renderCalendar());
        });

        function formatTime(dateStr) {
            const date = new Date(dateStr);
            return date.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
        }

        function escapeHtml(text) {
            const map = {
                '&': '&amp;',
                '<': '&lt;',
                '>': '&gt;',
                '"': '&quot;',
                "'": '&#039;'
            };
            return String(text || '').replace(/[&<>"']/g, (char) => map[char]);
        }

        initCalendar();
    });
</script>

