@extends('layouts.public')

@section('title', 'About Tima-Ade — Purpose, People & Possibility')
@section('meta_description', 'Discover Tima-Ade University, its mission, values, academic community, and commitment to meaningful impact.')

@section('content')
@php($images = $aboutImages ?? config('about.images'))
<section class="about-premium-hero position-relative overflow-hidden text-white">
    <img src="{{ asset($images['hero']['src']) }}" alt="{{ $images['hero']['alt'] }}" class="about-premium-hero-image">
    <div class="about-premium-hero-overlay"></div>
    <div class="container position-relative py-5"><div class="row align-items-end min-vh-75 py-5"><div class="col-xl-8 col-lg-10 py-5 about-reveal">
        <p class="about-kicker">ABOUT TIMA-ADE</p><h1 class="about-display">Where knowledge becomes purpose.</h1>
        <p class="about-hero-lead">Tima-Ade University is a learning community in Gabiley, Somaliland, committed to thoughtful education, academic quality, innovation, and the development of people who contribute with purpose.</p>
        <div class="d-flex flex-wrap gap-3 mt-4"><a href="#who-we-are" class="btn btn-light px-4 py-3 fw-semibold">Discover Tima-Ade <i class="bi bi-arrow-down-right ms-2"></i></a><a href="{{ route('public.about.campuses') }}" class="btn btn-outline-light px-4 py-3 fw-semibold">Explore Our Campuses <i class="bi bi-arrow-up-right ms-2"></i></a></div>
        <div class="about-scroll-cue mt-5"><span></span> Scroll to explore</div>
    </div></div></div>
</section>

<section id="who-we-are" class="about-editorial-section bg-white"><div class="container py-5 py-lg-6"><div class="row g-5 align-items-center"><div class="col-lg-5 about-reveal"><p class="about-kicker text-danger">WHO WE ARE</p><h2 class="about-section-title">A university with ambition, rooted in place.</h2></div><div class="col-lg-7 about-reveal"><p class="about-lead-copy">Tima-Ade University brings together committed educators, curious students, and partners who believe education should open opportunity and serve the public good.</p><p class="text-muted mb-0">Our approach connects strong academic foundations with practical learning, character development, leadership, and a responsibility to the communities around us. Students are encouraged to question deeply, work generously, and carry their learning into the world.</p></div></div></div></section>

<section class="about-story-section about-dark-section"><div class="container py-5 py-lg-6"><div class="row g-5"><div class="col-lg-4 about-reveal"><p class="about-kicker text-info">OUR STORY</p><h2 class="about-section-title text-white">Built carefully. Moving forward with purpose.</h2><p class="text-white-50 mt-4">Tima-Ade’s story is an ongoing commitment to make high-quality education matter in the lives of students and communities.</p></div><div class="col-lg-7 offset-lg-1 about-reveal"><div class="about-timeline">
@foreach ([['Foundation', 'Established around a clear belief in accessible, purposeful higher education.'], ['Academic community', 'Educators, students, and partners gathered around strong teaching and practical learning.'], ['Growing impact', 'The university continues to develop through inquiry, innovation, and engagement with the region it serves.'], ['The next chapter', 'A trusted institution taking the next considered steps for Somaliland and the wider world.']] as $index => $story)
<div class="about-timeline-item"><span class="about-timeline-number">0{{ $index + 1 }}</span><div><p class="about-timeline-label">{{ $story[0] }}</p><p class="mb-0 text-white-50">{{ $story[1] }}</p></div></div>
@endforeach
</div></div></div></div></section>

<section class="about-mission-section bg-light"><div class="container py-5 py-lg-6"><div class="row g-0 about-reveal"><div class="col-lg-6 p-4 p-md-5 bg-white border"><p class="about-kicker text-danger">OUR MISSION</p><h2 class="about-card-title">Education that develops capability and serves society.</h2><p class="text-muted mb-0">We provide quality education that develops capable graduates, encourages innovation, builds character, and prepares students to contribute responsibly to their communities.</p></div><div class="col-lg-6 p-4 p-md-5 bg-navy text-white"><p class="about-kicker text-info">OUR VISION</p><h2 class="about-card-title text-white">A respected institution known for excellence, innovation, and leadership.</h2><p class="text-white-50 mb-0">Tima-Ade will grow as a trusted center of learning and positive societal impact, recognized for the quality of its graduates and the relevance of its work.</p></div></div></div></section>

<section class="about-values-section bg-white"><div class="container py-5 py-lg-6"><div class="row align-items-end g-4 mb-5 about-reveal"><div class="col-lg-7"><p class="about-kicker text-danger">WHAT GUIDES US</p><h2 class="about-section-title mb-0">Core values, made visible in everyday work.</h2></div><div class="col-lg-4 offset-lg-1"><p class="text-muted mb-0">The standards we bring to classrooms, partnerships, decisions, and relationships.</p></div></div><div class="row g-0 border-start border-top">
@foreach ([['bi-stars', 'Excellence', 'We hold our work to a high standard and keep improving it.'], ['bi-shield-check', 'Integrity', 'We act with honesty, courage, and accountability.'], ['bi-lightbulb', 'Innovation', 'We welcome ideas that create meaningful progress.'], ['bi-compass', 'Leadership', 'We prepare people to lead with judgment and purpose.'], ['bi-book', 'Knowledge', 'We value inquiry, evidence, and lifelong learning.'], ['bi-scale', 'Responsibility', 'We consider the lasting effect of our choices.'], ['bi-heart', 'Respect', 'We make space for dignity, difference, and belonging.'], ['bi-globe2', 'Community', 'We connect our work to the needs of society.']] as $value)
<div class="col-md-6 col-lg-3 reveal-on-scroll"><article class="about-value-cell h-100"><i class="bi {{ $value[0] }} text-danger fs-4"></i><h3 class="h5 fw-bold mt-4">{{ $value[1] }}</h3><p class="small text-muted mb-0">{{ $value[2] }}</p></article></div>
@endforeach
</div></div></section>

<section class="about-leadership-section bg-light"><div class="container py-5 py-lg-6"><div class="row g-5 align-items-center"><div class="col-lg-5 about-reveal"><div class="about-leadership-image"><img src="{{ asset($images['community']['src']) }}" alt="{{ $images['community']['alt'] }}" class="img-fluid"><div class="about-image-caption"><span>Leadership message</span><small>Office of the University Leadership</small></div></div></div><div class="col-lg-6 offset-lg-1 about-reveal"><p class="about-kicker text-danger">FROM UNIVERSITY LEADERSHIP</p><blockquote class="about-quote">“The future is shaped by the quality of the people we equip to meet it.”</blockquote><p class="text-muted">At Tima-Ade, we believe a university’s deepest contribution is measured in the confidence, competence, and conscience of its graduates. We are committed to building that contribution patiently, together.</p><p class="about-signature">Tima-Ade University</p><p class="small text-muted mb-0">Official leadership name and portrait to be published following institutional confirmation.</p></div></div></div></section>

<section class="about-academic-section bg-white"><div class="container py-5 py-lg-6"><div class="row g-5"><div class="col-lg-5 about-reveal"><p class="about-kicker text-danger">ACADEMIC EXCELLENCE</p><h2 class="about-section-title">A serious education for a changing world.</h2></div><div class="col-lg-7 about-reveal"><p class="about-lead-copy">We invest in quality teaching, qualified educators, research-minded learning, and modern approaches that keep education relevant to students, industry, and community.</p><div class="row g-4 mt-2"><div class="col-sm-6"><h3 class="h5 fw-bold">Teaching with care</h3><p class="small text-muted">Clear foundations, thoughtful guidance, and an environment that supports student development.</p></div><div class="col-sm-6"><h3 class="h5 fw-bold">Learning through inquiry</h3><p class="small text-muted">Research and practical projects help students connect knowledge to real challenges.</p></div><div class="col-sm-6"><h3 class="h5 fw-bold">Relevant preparation</h3><p class="small text-muted">Communication, judgment, and initiative are developed alongside academic capability.</p></div><div class="col-sm-6"><h3 class="h5 fw-bold">Growing together</h3><p class="small text-muted">A culture of mentorship and collaboration helps learners make confident progress.</p></div></div></div></div></div></section>

<section class="about-life-section position-relative overflow-hidden text-white"><img src="{{ asset($images['classroom']['src']) }}" alt="{{ $images['classroom']['alt'] }}" class="about-life-image"><div class="about-life-overlay"></div><div class="container position-relative py-5 py-lg-6"><div class="row g-5"><div class="col-lg-5 about-reveal"><p class="about-kicker text-info">UNIVERSITY LIFE</p><h2 class="about-section-title text-white">More than a place to study.</h2><p class="text-white-50 mt-4">Students find room to learn, lead, experiment, connect, and grow into the people their communities need.</p></div><div class="col-lg-6 offset-lg-1 about-reveal"><div class="row g-4"><div class="col-sm-6"><p class="about-feature-index">01</p><h3 class="h5 text-white">Learning</h3><p class="small text-white-50">A rigorous, supportive academic environment.</p></div><div class="col-sm-6"><p class="about-feature-index">02</p><h3 class="h5 text-white">Student life</h3><p class="small text-white-50">Belonging, collaboration, and discovery.</p></div><div class="col-sm-6"><p class="about-feature-index">03</p><h3 class="h5 text-white">Leadership</h3><p class="small text-white-50">Initiative and responsibility through experience.</p></div><div class="col-sm-6"><p class="about-feature-index">04</p><h3 class="h5 text-white">Innovation</h3><p class="small text-white-50">Ideas connected to real opportunities.</p></div></div></div></div></div></section>

<section class="about-facilities-section bg-light"><div class="container py-5 py-lg-6"><div class="row align-items-end mb-5 about-reveal"><div class="col-lg-7"><p class="about-kicker text-danger">FACILITIES & CAMPUS LIFE</p><h2 class="about-section-title mb-0">Spaces that support the work of learning.</h2></div><div class="col-lg-4 offset-lg-1"><p class="text-muted mb-0">Explore the project’s existing campus, classroom, laboratory, library, and technology imagery.</p></div></div><div class="row g-3 about-gallery about-reveal"><div class="col-lg-7"><img src="{{ asset($images['library']['src']) }}" alt="{{ $images['library']['alt'] }}" class="w-100 h-100 object-fit-cover"></div><div class="col-lg-5"><div class="row g-3 h-100"><div class="col-6"><img src="{{ asset($images['laboratory']['src']) }}" alt="{{ $images['laboratory']['alt'] }}" class="w-100 h-100 object-fit-cover"></div><div class="col-6"><img src="{{ asset($images['technology']['src']) }}" alt="{{ $images['technology']['alt'] }}" class="w-100 h-100 object-fit-cover"></div><div class="col-12"><img src="{{ asset($images['event']['src']) }}" alt="{{ $images['event']['alt'] }}" class="w-100 h-100 object-fit-cover"></div></div></div></div></div></section>

<section class="about-difference-section bg-white"><div class="container py-5 py-lg-6"><div class="row g-5"><div class="col-lg-4 about-reveal"><p class="about-kicker text-danger">THE TIMA-ADE DIFFERENCE</p><h2 class="about-section-title">Why Tima-Ade?</h2><p class="text-muted">A university shaped around purposeful learning, human potential, and public contribution.</p></div><div class="col-lg-7 offset-lg-1"><div class="row g-4 about-reveal">@foreach ([['bi-mortarboard', 'Academic excellence', 'Purposeful study grounded in quality teaching.'], ['bi-people', 'Student-centered education', 'An environment designed around student growth.'], ['bi-cpu', 'Innovation & technology', 'Learning connected to ideas and practical challenges.'], ['bi-compass', 'Leadership development', 'Character and judgment built through experience.'], ['bi-building', 'Modern learning', 'Spaces and approaches that support meaningful work.'], ['bi-globe2', 'Community impact', 'A university committed to the society around it.']] as $reason)<div class="col-md-6"><div class="d-flex gap-3"><i class="bi {{ $reason[0] }} fs-4 text-danger"></i><div><h3 class="h5 fw-bold">{{ $reason[1] }}</h3><p class="small text-muted">{{ $reason[2] }}</p></div></div></div>@endforeach</div></div></div></div></section>

<section class="about-impact-section about-dark-section"><div class="container py-5 py-lg-6"><div class="row g-5"><div class="col-lg-5 about-reveal"><p class="about-kicker text-info">INSTITUTIONAL IMPACT</p><h2 class="about-section-title text-white">Knowledge that stays connected to life.</h2></div><div class="col-lg-7 about-reveal"><div class="row g-4"><div class="col-sm-6"><h3 class="about-impact-title">Education</h3><p class="text-white-50">Expanding knowledge, confidence, and opportunity for the next generation.</p></div><div class="col-sm-6"><h3 class="about-impact-title">Leadership</h3><p class="text-white-50">Preparing people to take thoughtful responsibility in organizations and communities.</p></div><div class="col-sm-6"><h3 class="about-impact-title">Innovation</h3><p class="text-white-50">Encouraging ideas, research, and practical solutions for a changing region.</p></div><div class="col-sm-6"><h3 class="about-impact-title">Opportunity</h3><p class="text-white-50">Creating pathways for graduates to contribute to a more capable future.</p></div></div></div></div></div></section>

<section class="about-preview-section bg-light"><div class="container py-5 py-lg-6"><div class="row g-4"><div class="col-lg-6"><div class="about-preview-panel h-100"><p class="about-kicker text-danger">GOVERNANCE</p><h2 class="about-card-title">Meet the Board of Directors</h2><p class="text-muted">Explore the university’s governance framework and verified board information.</p><a href="{{ route('public.about.board') }}" class="fw-bold text-danger text-decoration-none">Meet the Board of Directors <i class="bi bi-arrow-right ms-1"></i></a></div></div><div class="col-lg-6"><div class="about-preview-panel h-100"><p class="about-kicker text-danger">PLACES TO BELONG</p><h2 class="about-card-title">Explore Our Campuses</h2><p class="text-muted">Discover the confirmed Gabiley location and current campus information.</p><a href="{{ route('public.about.campuses') }}" class="fw-bold text-danger text-decoration-none">Explore Our Campuses <i class="bi bi-arrow-right ms-1"></i></a></div></div></div></div></section>

<section class="about-final-cta bg-navy text-white"><div class="container py-5 py-lg-6"><div class="row align-items-end g-5"><div class="col-lg-8 about-reveal"><p class="about-kicker text-info">YOUR NEXT CHAPTER</p><h2 class="about-display mb-0">Discover the Tima-Ade Experience</h2><p class="about-hero-lead mt-4 mb-0">Explore the people, programmes, and places that make Tima-Ade University a meaningful place to begin.</p></div><div class="col-lg-4 about-reveal"><div class="d-flex flex-column gap-3"><a href="{{ route('public.academics') }}" class="btn btn-light px-4 py-3 fw-semibold">Explore Programs <i class="bi bi-arrow-up-right ms-2"></i></a><a href="{{ route('public.about.campuses') }}" class="btn btn-outline-light px-4 py-3 fw-semibold">Explore Campuses <i class="bi bi-arrow-up-right ms-2"></i></a></div></div></div></div></section>
@endsection
