@extends('layouts.public')

@php
    $images = $admissionsImages ?? config('admissions.images');
    $pages = [
        'how-to-apply' => ['label' => 'Admissions guide', 'title' => 'How to Apply', 'intro' => 'A clear place to begin your application planning. Confirm current instructions with the university before submitting information.', 'heading' => 'A considered path forward.', 'copy' => 'The sequence below is general guidance for planning. It is not presented as an official set of university stages.', 'items' => ['Explore your options', 'Review current requirements', 'Prepare the information requested', 'Complete the official application or inquiry', 'Review next steps with the university']],
        'requirements' => ['label' => 'Admissions information', 'title' => 'Admission Requirements', 'intro' => 'A structured requirements portal for applicants seeking current, confirmed entry guidance.', 'heading' => 'Official requirements are not yet published here.', 'copy' => 'Entry requirements can vary by academic pathway. Confirm qualifications, supporting documents, and eligibility with the university before applying.', 'items' => ['Academic requirements: to be confirmed', 'Supporting documentation: to be confirmed', 'Program-specific considerations: to be confirmed', 'International requirements: to be confirmed']],
        'application-process' => ['label' => 'Application process', 'title' => 'Application Process', 'intro' => 'A planning framework for understanding the information and decisions that usually surround an application.', 'heading' => 'Clarity at every step.', 'copy' => 'Use this framework while the university confirms the exact process, timelines, and responsible offices.', 'items' => ['Application begins', 'Information and preparation', 'Application submission', 'Review and next steps', 'Applicant communication']],
        'dates' => ['label' => 'Admissions planning', 'title' => 'Important Dates', 'intro' => 'A dependable home for application periods, decisions, enrollment milestones, and official notices when published.', 'heading' => 'No official dates have been published here.', 'copy' => 'Dates are intentionally not fabricated. Contact the university or return to this page for the current admissions calendar.', 'items' => ['Application periods: to be announced', 'Admission milestones: to be announced', 'Enrollment dates: to be announced', 'Important notices: to be announced']],
        'fees' => ['label' => 'Financial information', 'title' => 'Fees & Funding', 'intro' => 'A clear home for verified application, tuition, registration, scholarship, and financial-support information.', 'heading' => 'Official amounts are pending confirmation.', 'copy' => 'No fees or funding figures are shown until they are confirmed by the university. Contact Admissions for current financial information.', 'items' => ['Application fee: to be confirmed', 'Tuition and registration: to be confirmed', 'Additional costs: to be confirmed', 'Funding opportunities: to be confirmed']],
        'international' => ['label' => 'International admissions', 'title' => 'International Admissions', 'intro' => 'A prepared space for applicants outside the local context, with guidance added as it is officially confirmed.', 'heading' => 'International guidance is being prepared.', 'copy' => 'Applicants should contact the university directly for current academic-document, immigration, visa, language, and arrival information.', 'items' => ['Application guidance: to be confirmed', 'Academic documentation: to be confirmed', 'Immigration and visa information: to be confirmed', 'Arrival and student support: to be confirmed']],
        'faq' => ['label' => 'Admissions support', 'title' => 'Frequently Asked Questions', 'intro' => 'A considered home for common admissions questions and official university answers.', 'heading' => 'Answers will appear here as they are confirmed.', 'copy' => 'The questions below identify the information applicants commonly need. No answer is presented as official until it has been published by the university.', 'items' => ['How do I apply?', 'What documents are required?', 'When are applications due?', 'How can I contact Admissions?']],
    ];
    $content = $pages[$page];
    $nav = ['public.admissions' => 'Overview', 'public.admissions.how-to-apply' => 'How to Apply', 'public.admissions.requirements' => 'Requirements', 'public.admissions.process' => 'Application Process', 'public.admissions.dates' => 'Important Dates', 'public.admissions.fees' => 'Fees & Funding', 'public.admissions.international' => 'International', 'public.admissions.faq' => 'FAQ'];
@endphp

@section('title', $content['title'] . ' — Tima-Ade University')
@section('meta_description', $content['intro'])
@section('content')
<div class="admissions-info-page">
    <section class="admissions-info-hero position-relative overflow-hidden text-white" aria-labelledby="admissions-info-title">
        <img src="{{ asset($images['hero']['src']) }}" alt="{{ $images['hero']['alt'] }}" class="admissions-info-hero-image">
        <div class="admissions-info-hero-overlay"></div>
        <div class="container position-relative py-5"><div class="row align-items-end min-vh-50 py-5"><div class="col-lg-8 py-5"><p class="admissions-kicker text-info">{{ strtoupper($content['label']) }}</p><h1 id="admissions-info-title" class="admissions-info-display">{{ $content['title'] }}</h1><p class="admissions-info-lead">{{ $content['intro'] }}</p></div></div></div>
    </section>
    <nav class="admissions-section-nav" aria-label="Admissions pages"><div class="container"><div class="admissions-section-nav-scroll">@foreach($nav as $routeName => $label)<a class="{{ request()->routeIs($routeName) ? 'is-current' : '' }}" href="{{ route($routeName) }}" @if(request()->routeIs($routeName)) aria-current="page" @endif>{{ $label }}</a>@endforeach</div></div></nav>
    <main class="bg-white"><div class="container py-5 py-lg-6"><div class="row g-5 align-items-start"><div class="col-lg-5"><p class="admissions-kicker text-danger">{{ strtoupper($content['label']) }}</p><h2 class="admissions-section-title">{{ $content['heading'] }}</h2><p class="admissions-info-copy">{{ $content['copy'] }}</p><div class="d-flex flex-wrap gap-3 mt-4"><a href="{{ route('public.admissions') }}" class="btn btn-crimson px-4 py-3">Admissions overview <i class="bi bi-arrow-right ms-2" aria-hidden="true"></i></a><a href="{{ route('public.contact') }}" class="btn btn-outline-dark px-4 py-3">Contact the university</a></div></div><div class="col-lg-7">
        @if($page === 'faq')
            <div class="admissions-faq" id="admissions-faq-list">@foreach($content['items'] as $index => $question)<article class="admissions-faq-item"><h3 class="mb-0"><button class="admissions-faq-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-answer-{{ $index }}" aria-expanded="false" aria-controls="faq-answer-{{ $index }}">{{ $question }}<i class="bi bi-plus-lg" aria-hidden="true"></i></button></h3><div id="faq-answer-{{ $index }}" class="collapse" data-bs-parent="#admissions-faq-list"><div class="admissions-faq-answer">Official guidance for this question is not currently published. Please contact the university for a confirmed answer.</div></div></article>@endforeach</div>
        @else
            <div class="admissions-info-list">@foreach($content['items'] as $index => $item)<article><span>0{{ $index + 1 }}</span><p>{{ $item }}</p></article>@endforeach</div>
        @endif
    </div></div></div></main>
    <section class="admissions-info-support bg-light" aria-labelledby="support-title"><div class="container py-5"><div class="row g-4 align-items-center"><div class="col-lg-6"><img src="{{ asset($images['learning']['src']) }}" alt="{{ $images['learning']['alt'] }}" class="admissions-info-image" loading="lazy"></div><div class="col-lg-6"><p class="admissions-kicker text-danger">NEXT STEP</p><h2 id="support-title" class="admissions-card-title">Keep your questions close.</h2><p class="admissions-info-copy">Review the available guidance, explore academic programs, and use the official contact channel whenever a detail needs confirmation.</p><a href="{{ route('public.programs') }}" class="fw-bold text-danger text-decoration-none">Explore academic programs <i class="bi bi-arrow-up-right ms-1" aria-hidden="true"></i></a></div></div></div></section>
</div>
@endsection