@extends('layouts.public')

@php
    $pages = [
        'learning' => ['label' => 'Digital learning', 'title' => 'Learning & Courses', 'intro' => 'A focused entry point to the learning tools already available within the Tima-Ade digital campus.', 'heading' => 'Learning resources belong in one clear place.', 'copy' => 'Sign in to access the learning areas available to your role. Public course and resource details are not invented here.', 'items' => ['Student course access', 'Course materials', 'Assignments and academic activities', 'Teacher learning management'], 'hero_image' => 'images/home/tech.jpg', 'hero_alt' => 'Digital learning technology at Tima-Ade University'],
        'resources' => ['label' => 'Academic resources', 'title' => 'Academic Resources', 'intro' => 'A structured place for approved academic materials and university resources as they become available.', 'heading' => 'Resources will appear here when published.', 'copy' => 'This page does not claim library databases, journals, subscriptions, or repositories that are not currently connected to the public site.', 'items' => ['Academic materials: available through the portal when assigned', 'Library resources: to be confirmed', 'Research resources: to be confirmed', 'Student guides: to be confirmed'], 'hero_image' => 'images/home/library.jpg', 'hero_alt' => 'University library learning environment'],
        'student-services' => ['label' => 'Student support', 'title' => 'Student Services', 'intro' => 'A clear route to the student-facing services currently represented in the university application.', 'heading' => 'Keep the essentials within reach.', 'copy' => 'Authenticated students and families can use the existing portal for the services available to their role. Contact the university when you need help finding the right channel.', 'items' => ['Student dashboard', 'Notices and announcements', 'Attendance and academic information', 'Fees and student records'], 'hero_image' => 'images/home/community.jpg', 'hero_alt' => 'Tima-Ade University community environment'],
        'help' => ['label' => 'E-Campus support', 'title' => 'Help & Support', 'intro' => 'A calm starting point when you need assistance with the Tima-Ade digital campus.', 'heading' => 'Start with the right support channel.', 'copy' => 'Sign in to see the tools available to your role, or contact the university directly for questions that are not answered by the existing portal.', 'items' => ['Portal access: use the existing sign-in flow', 'Student and parent support: contact the university', 'Learning access: check your authenticated dashboard', 'General questions: use the Contact page'], 'hero_image' => 'images/home/classroom.jpg', 'hero_alt' => 'Students learning in a Tima-Ade classroom'],
    ];
    $content = $pages[$page];
    $nav = ['public.facilities' => 'Overview', 'public.e-campus.learning' => 'Learning & Courses', 'public.e-campus.resources' => 'Academic Resources', 'public.e-campus.student-services' => 'Student Services', 'public.e-campus.help' => 'Help & Support'];
@endphp

@section('title', $content['title'] . ' — Tima-Ade University')
@section('meta_description', $content['intro'])
@section('content')
<div class="e-campus-info-page">
    <section class="e-campus-info-hero position-relative overflow-hidden text-white" aria-labelledby="e-campus-info-title">
        <img src="{{ asset($content['hero_image']) }}" alt="{{ $content['hero_alt'] }}" class="e-campus-info-hero-image">
        <div class="e-campus-info-hero-overlay"></div>
        <div class="container position-relative py-5"><div class="row align-items-end min-vh-50 py-5"><div class="col-lg-8 py-5"><p class="e-campus-kicker text-info">{{ strtoupper($content['label']) }}</p><h1 id="e-campus-info-title" class="e-campus-info-display">{{ $content['title'] }}</h1><p class="e-campus-info-lead">{{ $content['intro'] }}</p></div></div></div>
    </section>
    <nav class="e-campus-section-nav" aria-label="E-Campus pages"><div class="container"><div class="e-campus-section-nav-scroll">@foreach($nav as $routeName => $label)<a class="{{ request()->routeIs($routeName) ? 'is-current' : '' }}" href="{{ route($routeName) }}" @if(request()->routeIs($routeName)) aria-current="page" @endif>{{ $label }}</a>@endforeach</div></div></nav>
    <main class="bg-white"><div class="container py-5 py-lg-6"><div class="row g-5 align-items-start"><div class="col-lg-5"><p class="e-campus-kicker text-danger">{{ strtoupper($content['label']) }}</p><h2 class="e-campus-section-title">{{ $content['heading'] }}</h2><p class="e-campus-info-copy">{{ $content['copy'] }}</p><div class="d-flex flex-wrap gap-3 mt-4"><a href="{{ route('dashboard') }}" class="btn btn-crimson px-4 py-3">Enter E-Campus <i class="bi bi-arrow-up-right ms-2" aria-hidden="true"></i></a><a href="{{ route('public.contact') }}" class="btn btn-outline-dark px-4 py-3">Contact the university</a></div></div><div class="col-lg-7"><div class="e-campus-info-list">@foreach($content['items'] as $index => $item)<article><span>0{{ $index + 1 }}</span><p>{{ $item }}</p></article>@endforeach</div></div></div></div></main>
    <section class="bg-light"><div class="container py-5"><div class="row g-4 align-items-center"><div class="col-lg-6"><p class="e-campus-kicker text-danger">CONNECTED CAMPUS</p><h2 class="e-campus-card-title">One university. Clear digital pathways.</h2></div><div class="col-lg-6"><p class="e-campus-info-copy">Use the existing authenticated portal for role-specific tools, and return here for the public view of E-Campus services.</p><a href="{{ route('public.facilities') }}" class="fw-bold text-danger text-decoration-none">Return to E-Campus overview <i class="bi bi-arrow-right ms-1" aria-hidden="true"></i></a></div></div></div></section>
</div>
@endsection
