@extends('layouts.public')
@section('title', 'Academic Calendar — Tima-Ade University')
@section('meta_description', 'View the Tima-Ade University academic calendar — registration, teaching periods, examinations, and holidays as they are officially confirmed.')
@section('content')
@php($images = $programImages ?? config('programs.images'))
<section class="programs-hero position-relative overflow-hidden text-white"><img src="{{ asset($images['hero']['src']) }}" alt="{{ $images['hero']['alt'] }}" class="programs-hero-image"><div class="programs-hero-overlay"></div><div class="container position-relative py-5"><div class="row align-items-end min-vh-50 py-5"><div class="col-lg-8 py-5"><p class="programs-kicker text-info">ACADEMIC CALENDAR</p><h1 class="programs-display">Plan the year with clarity.</h1><p class="programs-hero-lead">A future-ready academic calendar for students, faculty, and families. Official dates will be published here as they are confirmed.</p></div></div></div></section>
<section class="bg-white"><div class="container py-5 py-lg-6"><div class="row g-5"><div class="col-lg-5"><p class="programs-kicker text-danger">ACADEMIC YEAR</p><h2 class="programs-section-title">A reliable reference for the university community.</h2><p class="text-muted">Use this page to find teaching periods, registration, examinations, holidays, and other important dates. No dates are shown until officially confirmed by Tima-Ade University.</p></div><div class="col-lg-7"><div class="programs-calendar-list">@foreach ([['01', 'Registration period', 'Official registration dates to be confirmed'], ['02', 'Teaching period', 'Official teaching dates to be confirmed'], ['03', 'Examination period', 'Official examination dates to be confirmed'], ['04', 'Breaks and holidays', 'Official holiday dates to be confirmed']] as $item)<article class="programs-calendar-item"><span>{{ $item[0] }}</span><div><h3>{{ $item[1] }}</h3><p>{{ $item[2] }}</p></div><i class="bi bi-arrow-right"></i></article>@endforeach</div></div></div></div></section>
<section class="bg-light"><div class="container py-5 py-lg-6"><div class="row g-4"><div class="col-lg-7"><img src="{{ asset($images['classroom']['src']) }}" alt="{{ $images['classroom']['alt'] }}" class="programs-feature-image" loading="lazy"></div><div class="col-lg-5"><p class="programs-kicker text-danger">IMPORTANT DATES</p><h2 class="programs-card-title">Dates that support good preparation.</h2><p class="text-muted">The calendar will become the official planning reference once the university confirms the academic year schedule.</p><div class="programs-empty-state"><i class="bi bi-calendar3"></i><strong>Calendar entries pending confirmation</strong><span>Check back for verified academic dates.</span></div></div></div></div></section>
<section class="programs-dark-cta text-white"><div class="container py-5"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-4"><div><p class="programs-kicker text-info">KEEP EXPLORING</p><h2 class="programs-card-title text-white mb-0">Choose your next academic step.</h2></div><div class="d-flex flex-wrap gap-3"><a href="{{ route('public.programs') }}" class="btn btn-light px-4 py-3 fw-semibold">Academic Programs</a><a href="{{ route('public.admissions') }}" class="btn btn-outline-light px-4 py-3 fw-semibold">Admission</a></div></div></div></section>
@endsection
