@extends('layouts.public')
@section('title', 'Careers & Certifications — Tima-Ade University')
@section('meta_description', 'Explore career development and certification pathways connected to the Tima-Ade University academic experience.')
@section('content')
@php($images = $programImages ?? config('programs.images'))
<section class="programs-hero position-relative overflow-hidden text-white"><img src="{{ asset($images['technology']['src']) }}" alt="{{ $images['technology']['alt'] }}" class="programs-hero-image"><div class="programs-hero-overlay"></div><div class="container position-relative py-5"><div class="row align-items-end min-vh-50 py-5"><div class="col-lg-8 py-5"><p class="programs-kicker text-info">CAREERS &amp; CERTIFICATIONS</p><h1 class="programs-display">Turn learning into forward motion.</h1><p class="programs-hero-lead">A structured home for career-development and certification information, built to grow with verified university opportunities.</p></div></div></div></section>
<section class="bg-white"><div class="container py-5 py-lg-6"><div class="row g-5 align-items-center"><div class="col-lg-5"><p class="programs-kicker text-danger">PROFESSIONAL DEVELOPMENT</p><h2 class="programs-section-title">Preparation is part of the education.</h2><p class="text-muted">Tima-Ade’s academic environment is designed to develop knowledge, judgment, initiative, and the confidence to contribute beyond the classroom.</p></div><div class="col-lg-7"><img src="{{ asset($images['technology']['src']) }}" alt="{{ $images['technology']['alt'] }}" class="programs-feature-image" loading="lazy"></div></div></div></section>
<section class="bg-light"><div class="container py-5 py-lg-6"><div class="row g-5"><div class="col-lg-4"><p class="programs-kicker text-danger">CAREER JOURNEY</p><h2 class="programs-section-title">Discover. Learn. Develop. Progress.</h2><p class="text-muted">The specific services, certifications, and opportunities below remain open for official confirmation.</p></div><div class="col-lg-7 offset-lg-1"><div class="programs-journey">@foreach ([['01', 'Discover', 'Understand your interests and academic direction.'], ['02', 'Learn', 'Build strong foundations through the current academic programme.'], ['03', 'Develop', 'Strengthen capability, character, and practical confidence.'], ['04', 'Progress', 'Carry verified qualifications and experience into the next opportunity.']] as $item)<article><span>{{ $item[0] }}</span><div><h3>{{ $item[1] }}</h3><p>{{ $item[2] }}</p></div></article>@endforeach</div></div></div></div></section>
<section class="bg-white"><div class="container py-5 py-lg-6"><div class="row g-4"><div class="col-lg-6"><div class="programs-next-panel"><p class="programs-kicker text-danger">CERTIFICATIONS</p><h2 class="programs-card-title">Verified certification opportunities</h2><p class="text-muted">No certification has been listed here until an official programme, eligibility, duration, and awarding body are confirmed.</p><div class="programs-empty-state"><i class="bi bi-patch-check"></i><strong>Certification catalogue pending confirmation</strong><span>Replace this slot with approved certification data.</span></div></div></div><div class="col-lg-6"><div class="programs-next-panel"><p class="programs-kicker text-danger">CONNECT</p><h2 class="programs-card-title">Questions about your next step?</h2><p class="text-muted">Contact the university for current information about academic pathways and admissions.</p><a href="{{ route('public.contact') }}" class="fw-bold text-danger text-decoration-none">Contact Tima-Ade <i class="bi bi-arrow-right ms-1"></i></a></div></div></div></div></section>
<section class="programs-dark-cta text-white"><div class="container py-5"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-4"><div><p class="programs-kicker text-info">CONTINUE YOUR JOURNEY</p><h2 class="programs-card-title text-white mb-0">Explore the academic foundation.</h2></div><div class="d-flex flex-wrap gap-3"><a href="{{ route('public.programs') }}" class="btn btn-light px-4 py-3 fw-semibold">Academic Programs</a><a href="{{ route('public.admissions') }}" class="btn btn-outline-light px-4 py-3 fw-semibold">Admission</a></div></div></div></section>
@endsection
