@extends('layouts.public')

@section('title', 'News — Tima-Ade University')
@section('meta_description', 'Read verified Tima-Ade University news, notices, and announcements from the official information archive.')
@section('content')
<div class="student-life-news-page">
<section class="student-life-info-hero position-relative overflow-hidden text-white"><div class="student-life-news-hero-pattern"></div><div class="container position-relative py-5"><div class="row align-items-end min-vh-50 py-5"><div class="col-lg-8 py-5"><p class="student-life-kicker text-info">UNIVERSITY NEWS</p><h1 class="student-life-display">What is happening at Tima-Ade.</h1><p class="student-life-hero-lead">Read verified university notices, announcements, and bulletins from the official information archive.</p></div></div></div></section>
<section class="bg-light"><div class="container py-5 py-lg-6"><div class="row align-items-end g-4 mb-5"><div class="col-lg-7"><p class="student-life-kicker text-danger">OFFICIAL UPDATES</p><h2 class="student-life-section-title">The university newsroom.</h2></div><div class="col-lg-5"><p class="student-life-lead mb-0">This editorial view uses the same published notice data as the official noticeboard.</p></div></div><div class="student-life-news-list">@forelse($notices as $notice)<article class="student-life-news-item"><div class="student-life-news-date"><strong>{{ $notice->published_date->format('d') }}</strong><span>{{ $notice->published_date->format('M Y') }}</span></div><div><span class="student-life-news-category">{{ $notice->category }}</span><h3><a href="{{ route('public.notices.single', $notice) }}">{{ $notice->title }}</a></h3><p>{{ Str::limit($notice->content, 220) }}</p><a href="{{ route('public.notices.single', $notice) }}" class="fw-bold text-danger text-decoration-none">Read announcement <i class="bi bi-arrow-up-right ms-1"></i></a></div></article>@empty<div class="student-life-empty" role="status"><i class="bi bi-newspaper"></i><h3>No verified news stories yet.</h3><p>Official updates will appear here when published by the university.</p><a href="{{ route('public.notices') }}" class="btn btn-outline-danger">Visit the Noticeboard</a></div>@endforelse</div></div></section>
<section class="student-life-dark-section"><div class="container py-5"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-4"><div><p class="student-life-kicker text-info">KEEP EXPLORING</p><h2 class="student-life-card-title text-white mb-0">Stay close to the community.</h2></div><div class="d-flex flex-wrap gap-3"><a href="{{ route('public.student-life') }}" class="btn btn-light px-4 py-3 fw-semibold">Student Life</a><a href="{{ route('public.student-life.research') }}" class="btn btn-outline-light px-4 py-3 fw-semibold">Research</a></div></div></div></section>
</div>
@endsection
