@extends('layouts.public')

@php
    $images = $studentLifeImages ?? config('student-life.images');
    $content = [
        'alumni' => ['label' => 'Alumni community', 'title' => 'The Tima-Ade community beyond graduation.', 'intro' => 'A future-ready home for verified alumni stories, events, and connection opportunities.', 'heading' => 'Stay connected to the university community.', 'copy' => 'Official alumni programmes, directory information, events, and mentorship opportunities will be published here when confirmed by Tima-Ade University.', 'image' => 'community', 'items' => ['Alumni directory: to be confirmed', 'Networking opportunities: to be confirmed', 'Mentorship and career connections: to be confirmed', 'Alumni events and engagement: to be confirmed']],
        'research' => ['label' => 'Research and inquiry', 'title' => 'Ideas that deserve a closer look.', 'intro' => 'A serious space for verified research areas, projects, publications, and innovation stories.', 'heading' => 'Research information, carefully presented.', 'copy' => 'Research areas, projects, researchers, and publications will be added here only after official confirmation. The structure is ready for the university’s academic work.', 'image' => 'research', 'items' => ['Research areas: to be confirmed', 'Active projects: to be confirmed', 'Publications: to be confirmed', 'Innovation opportunities: to be confirmed']],
    ][$page];
@endphp

@section('title', $content['title'] . ' — Tima-Ade University')
@section('meta_description', $content['intro'])
@section('content')
<section class="student-life-info-hero position-relative overflow-hidden text-white"><img src="{{ asset($images[$content['image']]['src']) }}" alt="{{ $images[$content['image']]['alt'] }}" class="student-life-hero-image"><div class="student-life-hero-overlay"></div><div class="container position-relative py-5"><div class="row align-items-end min-vh-50 py-5"><div class="col-lg-8 py-5"><p class="student-life-kicker text-info">{{ strtoupper($content['label']) }}</p><h1 class="student-life-display">{{ $content['title'] }}</h1><p class="student-life-hero-lead">{{ $content['intro'] }}</p></div></div></div></section>
<section class="bg-white"><div class="container py-5 py-lg-6"><div class="row g-5"><div class="col-lg-5"><p class="student-life-kicker text-danger">{{ strtoupper($content['label']) }}</p><h2 class="student-life-section-title">{{ $content['heading'] }}</h2><p class="text-muted">{{ $content['copy'] }}</p><a href="{{ route('public.student-life') }}" class="btn btn-crimson px-4 py-3 fw-semibold mt-3">Return to Student Life <i class="bi bi-arrow-right ms-2"></i></a></div><div class="col-lg-7"><div class="student-life-info-list">@foreach($content['items'] as $index => $item)<article><span>0{{ $index + 1 }}</span><p>{{ $item }}</p></article>@endforeach</div></div></div></div></section>
<section class="bg-light"><div class="container py-5"><div class="row g-4 align-items-center"><div class="col-lg-6"><img src="{{ asset($images['learning']['src']) }}" alt="{{ $images['learning']['alt'] }}" class="student-life-feature-image" loading="lazy"></div><div class="col-lg-6"><p class="student-life-kicker text-danger">BUILDING THE ARCHIVE</p><h2 class="student-life-card-title">Structured for the information that comes next.</h2><p class="text-muted">Replace each clearly marked slot with approved university content when it becomes available. The presentation is ready without making unsupported claims.</p><a href="{{ route('public.contact') }}" class="fw-bold text-danger text-decoration-none">Contact the university <i class="bi bi-arrow-up-right ms-1"></i></a></div></div></div></section>
@endsection
