@extends('layouts.public')

@section('title', 'Student Life — Tima-Ade University')
@section('meta_description', 'Discover Student Life at Tima-Ade University — alumni connections, research and inquiry, and verified university news and announcements.')
@section('content')
@php($images = $studentLifeImages ?? config('student-life.images'))
<section class="student-life-hero position-relative overflow-hidden text-white"><img src="{{ asset($images['hero']['src']) }}" alt="{{ $images['hero']['alt'] }}" class="student-life-hero-image"><div class="student-life-hero-overlay"></div><div class="container position-relative py-5"><div class="row align-items-end min-vh-50 py-5"><div class="col-lg-8 py-5"><p class="student-life-kicker text-info">STUDENT LIFE</p><h1 class="student-life-display">A community that continues beyond the classroom.</h1><p class="student-life-hero-lead">Discover the people, ideas, and official university updates that shape the Tima-Ade experience.</p><div class="d-flex flex-wrap gap-3 mt-4"><a href="#student-life-explore" class="btn btn-light px-4 py-3 fw-semibold">Explore Student Life <i class="bi bi-arrow-down-right ms-2"></i></a><a href="{{ route('public.contact') }}" class="btn btn-outline-light px-4 py-3 fw-semibold">Connect with us <i class="bi bi-arrow-up-right ms-2"></i></a></div></div></div></div></section>
<section id="student-life-explore" class="bg-white"><div class="container py-5 py-lg-6"><div class="row g-5 align-items-end mb-5"><div class="col-lg-6"><p class="student-life-kicker text-danger">THE TIMA-ADE COMMUNITY</p><h2 class="student-life-section-title">Find the part of university life that matters to you.</h2></div><div class="col-lg-5 offset-lg-1"><p class="student-life-lead">Student Life brings together community connection, academic inquiry, alumni relationships, and verified university news in one clear place.</p></div></div><div class="row g-4"><div class="col-lg-4"><a class="student-life-feature" href="{{ route('public.student-life.alumni') }}"><img src="{{ asset($images['community']['src']) }}" alt="{{ $images['community']['alt'] }}"><div><p class="student-life-kicker text-info">01 · COMMUNITY</p><h3>Alumni</h3><span>Stay connected beyond graduation <i class="bi bi-arrow-up-right"></i></span></div></a></div><div class="col-lg-4"><a class="student-life-feature" href="{{ route('public.student-life.research') }}"><img src="{{ asset($images['research']['src']) }}" alt="{{ $images['research']['alt'] }}"><div><p class="student-life-kicker text-info">02 · INQUIRY</p><h3>Research</h3><span>Explore research information <i class="bi bi-arrow-up-right"></i></span></div></a></div><div class="col-lg-4"><a class="student-life-feature" href="{{ route('public.student-life.news') }}"><img src="{{ asset($images['event']['src']) }}" alt="{{ $images['event']['alt'] }}"><div><p class="student-life-kicker text-info">03 · UPDATES</p><h3>News</h3><span>Read verified university notices <i class="bi bi-arrow-up-right"></i></span></div></a></div></div></div></section>
<section class="student-life-dark-section"><div class="container py-5 py-lg-6"><div class="row g-5 align-items-center"><div class="col-lg-5"><p class="student-life-kicker text-info">A SHARED EXPERIENCE</p><h2 class="student-life-section-title text-white">Learn, connect, contribute.</h2><p class="text-white-50">The Student Life hub is designed to help visitors move naturally between community stories, academic inquiry, and official updates.</p></div><div class="col-lg-6 offset-lg-1"><img src="{{ asset($images['campus']['src']) }}" alt="{{ $images['campus']['alt'] }}" class="student-life-feature-image" loading="lazy"></div></div></div></section>
<section class="bg-light"><div class="container py-5"><div class="row g-4"><div class="col-md-4"><h3 class="h5 fw-bold">Learning in context</h3><p class="small text-muted">Connect student experience to the academic environment.</p></div><div class="col-md-4"><h3 class="h5 fw-bold">Community connection</h3><p class="small text-muted">Make room for relationships that last beyond campus.</p></div><div class="col-md-4"><h3 class="h5 fw-bold">Official information</h3><p class="small text-muted">Find current notices and announcements from the university.</p></div></div></div></section>
@endsection
