@extends('layouts.app')
@section('title', 'Applicants')
@section('breadcrumb')<li class="breadcrumb-item active">Applicants</li>@endsection
@section('content')
<div class="container-fluid px-0">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div><h3 class="page-title mb-1">Applicants</h3><p class="text-muted small mb-0">People represented by the existing admissions applications.</p></div>
    </div>
    <div class="card custom-card mb-4"><div class="card-body"><form method="GET" action="{{ route('admin.applicants') }}" class="row g-3"><div class="col-lg-4"><label class="form-label" for="applicant-search">Search applicants</label><input id="applicant-search" type="search" name="search" class="form-control" value="{{ request('search') }}" placeholder="Name, email, phone, or application reference"></div><div class="col-md-4 col-lg-2"><label class="form-label" for="applicant-status">Latest status</label><select id="applicant-status" name="status" class="form-select"><option value="">All statuses</option>@foreach(['submitted','under_review','approved','declined'] as $option)<option value="{{ $option }}" @selected($status === $option)>{{ ucfirst(str_replace('_', ' ', $option)) }}</option>@endforeach</select></div><div class="col-md-4 col-lg-2"><label class="form-label" for="applicant-from">From</label><input id="applicant-from" type="date" name="submitted_from" class="form-control" value="{{ request('submitted_from') }}"></div><div class="col-md-4 col-lg-2"><label class="form-label" for="applicant-to">To</label><input id="applicant-to" type="date" name="submitted_to" class="form-control" value="{{ request('submitted_to') }}"></div><div class="col-md-6 col-lg-1 d-flex align-items-end"><button class="btn btn-dark w-100" type="submit" aria-label="Search applicants"><i class="bi bi-search"></i></button></div><div class="col-md-6 col-lg-1 d-flex align-items-end"><a class="btn btn-outline-secondary w-100" href="{{ route('admin.applicants') }}">Clear</a></div></form></div></div>
    <div class="card custom-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Applicant</th><th>Email</th><th>Phone</th><th>Applications</th><th>Latest status</th><th>Latest application</th><th>Last updated</th><th></th></tr></thead><tbody>@forelse($applicants as $applicant)<tr><td class="fw-semibold">{{ $applicant->name }}</td><td>{{ $applicant->email }}</td><td>{{ $applicant->phone }}</td><td>{{ $applicant->application_count }}</td><td><span class="badge text-bg-secondary">{{ ucfirst(str_replace('_', ' ', $applicant->latest_status ?? 'Unknown')) }}</span></td><td>{{ \Carbon\Carbon::parse($applicant->latest_application_at)->format('d M Y') }}</td><td>{{ \Carbon\Carbon::parse($applicant->last_updated)->format('d M Y') }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.applicants.show', $applicant->representative_id) }}">View profile</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-5">No applicants match the current filters.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $applicants->links() }}</div></div>
</div>
@endsection
