@extends('layouts.app')
@section('title', 'Applicant Profile')
@section('breadcrumb')<li class="breadcrumb-item"><a href="{{ route('admin.applicants') }}">Applicants</a></li><li class="breadcrumb-item active">{{ $application->name }}</li>@endsection
@section('content')
<div class="container-fluid px-0">
    <div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="page-title mb-1">{{ $application->name }}</h3><p class="text-muted small mb-0">Applicant profile from existing admissions records</p></div><a href="{{ route('admin.applicants') }}" class="btn btn-outline-secondary">Back to applicants</a></div>
    <div class="row g-4">
        <div class="col-lg-5"><div class="card custom-card mb-4"><div class="card-body"><h5>Personal Information</h5><dl class="row mb-0"><dt class="col-sm-4">Name</dt><dd class="col-sm-8">{{ $application->name }}</dd><dt class="col-sm-4">Email</dt><dd class="col-sm-8">{{ $application->email }}</dd><dt class="col-sm-4">Phone</dt><dd class="col-sm-8">{{ $application->phone }}</dd></dl></div></div><div class="card custom-card"><div class="card-body"><h5>Academic Background</h5><dl class="row mb-0">@forelse(($application->education ?? []) as $label => $value)<dt class="col-sm-6 text-capitalize">{{ str_replace('_', ' ', $label) }}</dt><dd class="col-sm-6">{{ $value ?: 'Not provided' }}</dd>@empty<p class="text-muted mb-0">No academic information is recorded.</p>@endforelse</dl></div></div></div>
        <div class="col-lg-7"><div class="card custom-card"><div class="card-body"><h5>Application History</h5><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Reference</th><th>Program / Grade</th><th>Submitted</th><th>Updated</th><th>Status</th><th></th></tr></thead><tbody>@foreach($applications as $record)<tr><td class="fw-semibold">{{ $record->reference }}</td><td>{{ $record->grade_interested }}</td><td>{{ $record->created_at->format('d M Y') }}</td><td>{{ $record->updated_at->format('d M Y') }}</td><td><span class="badge text-bg-{{ $record->status === 'approved' ? 'success' : ($record->status === 'declined' ? 'danger' : ($record->status === 'under_review' ? 'warning' : 'secondary')) }}">{{ ucfirst(str_replace('_', ' ', $record->status)) }}</span></td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.applications.show', $record) }}">Open</a></td></tr>@endforeach</tbody></table></div></div></div><div class="card custom-card mt-4"><div class="card-body"><h5>Available summaries</h5><div class="row g-2"><div class="col-4"><span class="text-muted small d-block">Submitted documents</span><strong>{{ array_sum($documentSummary) }}</strong></div><div class="col-4"><span class="text-muted small d-block">Pending verification</span><strong>{{ $documentSummary['submitted'] }}</strong></div><div class="col-4"><span class="text-muted small d-block">Verified</span><strong>{{ $documentSummary['verified'] }}</strong></div></div><p class="text-muted small mt-3 mb-0">{{ $documentSummary['requires_correction'] }} document(s) require correction. @if($decision) Decision: {{ ucfirst($decision->status) }} on {{ $decision->decided_at->format('d M Y') }}@else No decision is recorded.@endif Interview and review history are shown only where supported by existing records.</p></div></div></div>
    </div>
</div>
@endsection
