@extends('layouts.app')

@section('title', 'Transcript')

@section('content')
<div class="container-fluid px-4 py-6 bg-light min-vh-100">
    <nav class="mb-3">
        @if(auth()->user()->isStudent())
            <a href="{{ route('transcripts.mine') }}" class="text-decoration-none">&laquo; Back to My Transcripts</a>
        @else
            <a href="{{ route('registrar.transcripts.index') }}" class="text-decoration-none">&laquo; Back to Transcripts</a>
        @endif
    </nav>

    <div class="card border-0 shadow-sm rounded-4">
        <div class="card-body p-4">
            <div class="d-flex justify-content-between flex-wrap mb-4">
                <div>
                    <h1 class="h3 mb-1" style="color:#1F2937;">Official Transcript</h1>
                    <p class="text-muted mb-0">{{ $transcript->student->user->name ?? 'N/A' }} — {{ $transcript->academic_year }}, {{ $transcript->term }}</p>
                </div>
                <div class="text-end">
                    <p class="mb-0 text-muted small">Cumulative GPA</p>
                    <h2 class="mb-0" style="color:#016ED5;">{{ number_format($transcript->gpa, 2) }}</h2>
                </div>
            </div>

            <div class="row g-3 mb-4">
                <div class="col-md-4">
                    <div class="p-3 bg-light rounded-3">
                        <p class="text-muted small mb-1">Total Credits</p>
                        <h4 class="mb-0">{{ $transcript->total_credits }}</h4>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 bg-light rounded-3">
                        <p class="text-muted small mb-1">Generated By</p>
                        <h6 class="mb-0">{{ $transcript->generatedBy->name ?? 'System' }}</h6>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="p-3 bg-light rounded-3">
                        <p class="text-muted small mb-1">Date Generated</p>
                        <h6 class="mb-0">{{ $transcript->generated_at?->format('M d, Y') }}</h6>
                    </div>
                </div>
            </div>

            <h5 class="mb-2">Subject Summary</h5>
            <pre class="bg-light p-3 rounded-3 mb-0" style="white-space: pre-wrap;">{{ $transcript->summary ?: 'No subject-level summary available.' }}</pre>
        </div>
    </div>
</div>
@endsection
