@extends('layouts.app')
@section('title', 'Invoice '.$invoice->invoice_number)
@section('content')
<div class="container-fluid px-4 py-4 bg-light min-vh-100">
    <div class="d-flex justify-content-between align-items-start mb-4"><div><p class="text-uppercase text-muted small fw-semibold mb-1">Student billing</p><h1 class="h2 mb-1">{{ $invoice->invoice_number }}</h1><p class="text-muted mb-0">{{ $invoice->student->user->name ?? 'Student' }} · Issued {{ $invoice->issue_date?->format('M d, Y') }}</p></div><span class="badge text-bg-light border">{{ ucfirst(str_replace('_', ' ', $invoice->status)) }}</span></div>
    <div class="row g-4"><div class="col-lg-8"><section class="card border-0 shadow-sm"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Fee type</th><th>Description</th><th class="text-end">Amount</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $item->fee_type }}</td><td>{{ $item->description }}</td><td class="text-end">₦{{ number_format($item->total_amount, 2) }}</td></tr>@endforeach</tbody></table></div></section></div><div class="col-lg-4"><section class="card border-0 shadow-sm"><div class="card-body"><dl class="row mb-0"><dt class="col-7">Subtotal</dt><dd class="col-5 text-end">₦{{ number_format($invoice->subtotal, 2) }}</dd><dt class="col-7">Discounts</dt><dd class="col-5 text-end">₦{{ number_format($invoice->discounts + $invoice->scholarship_amount, 2) }}</dd><dt class="col-7 fw-bold">Total</dt><dd class="col-5 text-end fw-bold">₦{{ number_format($invoice->total, 2) }}</dd><dt class="col-7">Paid</dt><dd class="col-5 text-end text-success">₦{{ number_format($invoice->amount_paid, 2) }}</dd><dt class="col-7">Balance</dt><dd class="col-5 text-end text-danger fw-bold">₦{{ number_format($invoice->balance, 2) }}</dd></dl></div></section></div></div>
    @if($invoice->payments->isNotEmpty())<section class="card border-0 shadow-sm mt-4"><div class="card-header bg-white"><h2 class="h5 mb-0">Payment history</h2></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Receipt</th><th>Date</th><th>Method</th><th class="text-end">Amount</th><th>Status</th></tr></thead><tbody>@foreach($invoice->payments as $payment)<tr><td>{{ $payment->receipt_number }}</td><td>{{ $payment->payment_date?->format('M d, Y') }}</td><td>{{ str_replace('_', ' ', $payment->payment_method) }}</td><td class="text-end">₦{{ number_format($payment->amount_paid, 2) }}</td><td>{{ ucfirst($payment->status) }}</td></tr>@endforeach</tbody></table></div></section>@endif
</div>
@endsection
