@extends('layouts.app')

@php
    $titles = ['communications' => 'Internal Communications', 'time' => 'Attendance & Leave', 'support' => 'Student Services Helpdesk', 'maintenance' => 'Facility & Resource Requests', 'hr' => 'HR & Payroll Overview'];
    $title = $titles[$section] ?? 'Staff Workspace';
@endphp

@section('title', $title)
@section('breadcrumb')<li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Staff Dashboard</a></li><li class="breadcrumb-item active" aria-current="page">{{ $title }}</li>@endsection

@section('content')
<div class="container-fluid px-0 staff-workspace">
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4">
        <div><p class="text-uppercase text-primary small fw-bold mb-1">Staff workspace</p><h1 class="h3 fw-bold mb-1">{{ $title }}</h1><p class="text-muted mb-0">Operational tools available to your staff account.</p></div>
        <a href="{{ route('dashboard') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i> Dashboard</a>
    </div>

    @if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger" role="alert">{{ $errors->first() }}</div>@endif

    @if($section === 'communications')
        <div class="card border-0 shadow-sm"><div class="card-body p-0">
            @forelse($notices as $notice)<article class="p-4 border-bottom"><div class="d-flex justify-content-between gap-3"><h2 class="h5 fw-bold mb-2">{{ $notice->title }}</h2><span class="badge text-bg-light align-self-start">{{ $notice->category }}</span></div><p class="mb-2">{{ strip_tags($notice->content) }}</p><time class="small text-muted" datetime="{{ optional($notice->published_date)->toDateString() }}">{{ optional($notice->published_date)->format('F j, Y') }}</time></article>@empty<div class="p-4 text-muted">No published communications are available.</div>@endforelse
        </div></div><div class="mt-3">{{ $notices->links() }}</div>
    @elseif($section === 'time')
        <div class="row g-4"><div class="col-lg-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5 fw-bold">Today</h2><p class="text-muted small">{{ $today?->attendance_date?->format('F j, Y') ?? now()->format('F j, Y') }}</p><dl class="row small"><dt class="col-6">Checked in</dt><dd class="col-6">{{ $today?->checked_in_at?->format('g:i A') ?? 'Not yet' }}</dd><dt class="col-6">Checked out</dt><dd class="col-6">{{ $today?->checked_out_at?->format('g:i A') ?? 'Not yet' }}</dd></dl><div class="d-flex gap-2">@if(!$today?->checked_in_at)<form method="POST" action="{{ route('staff.workspace.time.check-in') }}">@csrf<button class="btn btn-primary" type="submit">Check in</button></form>@elseif(!$today?->checked_out_at)<form method="POST" action="{{ route('staff.workspace.time.check-out') }}">@csrf<button class="btn btn-outline-primary" type="submit">Check out</button></form>@endif</div></div></div></div>
        <div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="card-header bg-white"><h2 class="h5 fw-bold mb-0">Leave request</h2></div><div class="card-body"><form method="POST" action="{{ route('leave-requests.store') }}" class="row g-3">@csrf<div class="col-md-6"><label class="form-label" for="leave_type_id">Leave type</label><select class="form-select" id="leave_type_id" name="leave_type_id" required><option value="">Select type</option>@foreach($leaveTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label" for="from_date">From</label><input class="form-control" id="from_date" type="date" name="from_date" required></div><div class="col-md-3"><label class="form-label" for="to_date">To</label><input class="form-control" id="to_date" type="date" name="to_date" required></div><div class="col-12"><label class="form-label" for="reason">Reason</label><textarea class="form-control" id="reason" name="reason" rows="3" maxlength="2000"></textarea></div><div class="col-12"><button class="btn btn-primary" type="submit">Submit request</button></div></form></div></div><div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white"><h2 class="h5 fw-bold mb-0">Recent attendance</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th scope="col">Date</th><th scope="col">In</th><th scope="col">Out</th></tr></thead><tbody>@forelse($logs as $log)<tr><td>{{ $log->attendance_date->format('M j, Y') }}</td><td>{{ $log->checked_in_at?->format('g:i A') ?? 'Not recorded' }}</td><td>{{ $log->checked_out_at?->format('g:i A') ?? 'Not recorded' }}</td></tr>@empty<tr><td colspan="3" class="text-muted">No attendance logs yet.</td></tr>@endforelse</tbody></table></div></div></div></div>
    @elseif(in_array($section, ['support', 'maintenance'], true))
        <div class="row g-4"><div class="col-lg-4"><div class="card border-0 shadow-sm"><div class="card-body"><h2 class="h5 fw-bold">New {{ $section === 'support' ? 'helpdesk ticket' : 'maintenance request' }}</h2><form method="POST" action="{{ route("staff.workspace.$section.store") }}" class="vstack gap-3">@csrf<label class="form-label mb-0" for="subject">Subject</label><input class="form-control" id="subject" name="subject" required maxlength="255"><label class="form-label mb-0" for="description">Details</label><textarea class="form-control" id="description" name="description" rows="5" required maxlength="4000"></textarea><button class="btn btn-primary" type="submit">Submit request</button></form></div></div></div><div class="col-lg-8"><div class="card border-0 shadow-sm"><div class="card-header bg-white"><h2 class="h5 fw-bold mb-0">Your requests</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th scope="col">Subject</th><th scope="col">Status</th><th scope="col">Created</th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{ $item->subject }}</strong><div class="small text-muted">{{ $item->description }}</div></td><td><span class="badge text-bg-light text-capitalize">{{ str_replace('_', ' ', $item->status) }}</span></td><td class="text-nowrap">{{ $item->created_at->format('M j, Y') }}</td></tr>@empty<tr><td colspan="3" class="text-muted">No requests submitted yet.</td></tr>@endforelse</tbody></table></div></div><div class="mt-3">{{ $items->links() }}</div></div></div>
    @else
        <div class="row g-4"><div class="col-lg-5"><div class="card border-0 shadow-sm h-100"><div class="card-body"><h2 class="h5 fw-bold">Staff profile</h2><dl class="row small mb-0"><dt class="col-5 text-muted">Name</dt><dd class="col-7">{{ auth()->user()->name }}</dd><dt class="col-5 text-muted">Employee ID</dt><dd class="col-7">{{ $employee?->employee_id ?? 'Not linked' }}</dd><dt class="col-5 text-muted">Department</dt><dd class="col-7">{{ $employee?->department ?? 'Not provided' }}</dd><dt class="col-5 text-muted">Designation</dt><dd class="col-7">{{ $employee?->designation ?? 'Not provided' }}</dd><dt class="col-5 text-muted">Email</dt><dd class="col-7 text-break">{{ auth()->user()->email }}</dd></dl></div></div></div><div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-header bg-white"><h2 class="h5 fw-bold mb-0">Paid payslips</h2></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th scope="col">Period</th><th scope="col">Net pay</th><th scope="col">Status</th><th scope="col"><span class="visually-hidden">Download</span></th></tr></thead><tbody>@forelse($payslips as $payslip)<tr><td>{{ $payslip->payrollPeriod?->name ?? $payslip->payrollPeriod?->start_date?->format('M Y') ?? 'Payroll period' }}</td><td>{{ number_format($payslip->net_salary, 2) }}</td><td><span class="badge text-bg-success">Paid</span></td><td><a class="btn btn-sm btn-outline-secondary" href="{{ route('staff.workspace.hr.payslips.download', $payslip) }}" aria-label="Download payslip"><i class="bi bi-download" aria-hidden="true"></i></a></td></tr>@empty<tr><td colspan="4" class="text-muted">No paid payslips are available.</td></tr>@endforelse</tbody></table></div></div><div class="alert alert-info mt-4" role="note">Official HR policies and university-wide employment notices are published in <a href="{{ route('staff.workspace.communications') }}">Communications</a>.</div></div></div>
    @endif
</div>
@endsection