'use client'

import Image from 'next/image'
import Link from 'next/link'
import { ArrowDownRight, ArrowRight, BookOpen, Brain, Briefcase, Building2, Compass, FlaskConical, Globe2, HeartHandshake, Lightbulb, Scale, ShieldCheck, Sparkles, Users } from 'lucide-react'
import { motion } from 'framer-motion'
import { AboutPage } from '../../components/AboutPageShell'

const values = [
  { icon: Sparkles, title: 'Excellence', text: 'We hold our work to a high standard and keep improving it.' },
  { icon: ShieldCheck, title: 'Integrity', text: 'We act with honesty, courage, and accountability.' },
  { icon: Lightbulb, title: 'Innovation', text: 'We welcome ideas that create meaningful progress.' },
  { icon: Compass, title: 'Leadership', text: 'We prepare people to lead with judgment and purpose.' },
  { icon: BookOpen, title: 'Knowledge', text: 'We value inquiry, evidence, and lifelong learning.' },
  { icon: Scale, title: 'Responsibility', text: 'We consider the lasting effect of our choices.' },
  { icon: HeartHandshake, title: 'Respect', text: 'We make space for dignity, difference, and belonging.' },
  { icon: Globe2, title: 'Community', text: 'We connect our work to the needs of society.' },
]

const timeline = [
  { label: 'Foundation', text: 'Tima-Ade University was established with a clear belief in the power of accessible, purposeful higher education.' },
  { label: 'Academic community', text: 'The institution brought educators, students, and partners together around strong teaching and practical learning.' },
  { label: 'Growing impact', text: 'Our community continues to develop through research, innovation, and engagement with the region we serve.' },
  { label: 'The next chapter', text: 'We are building a trusted university that equips future leaders for Somaliland and the wider world.' },
]

const experiences = [
  { icon: Brain, title: 'Learning', text: 'A rigorous, supportive environment where students build confidence and capability.' },
  { icon: Users, title: 'Student life', text: 'A connected community that makes space for belonging, collaboration, and discovery.' },
  { icon: Briefcase, title: 'Leadership', text: 'Practical opportunities to grow judgment, initiative, and a sense of responsibility.' },
  { icon: FlaskConical, title: 'Innovation', text: 'Research-minded learning that connects ideas to real challenges and opportunities.' },
]

export default function AboutTimaAde() {
  return (
    <AboutPage>
      <section className="relative flex min-h-[720px] items-end overflow-hidden bg-primary-900 text-white md:min-h-[780px]">
        <Image src="/images/home/campus.jpg" alt="Tima-Ade University campus" fill priority sizes="100vw" className="object-cover opacity-55" />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,24,55,0.96),rgba(7,24,55,0.56)_55%,rgba(7,24,55,0.26))]" />
        <div className="absolute inset-x-0 bottom-0 h-40 bg-gradient-to-t from-primary-900 to-transparent" />
        <div className="container-xl relative z-10 pb-16 pt-40 md:pb-24">
          <motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }} className="max-w-4xl">
            <p className="text-xs font-bold uppercase tracking-[0.24em] text-blue-200">About Tima-Ade</p>
            <h1 className="mt-6 max-w-4xl text-5xl font-bold leading-[0.98] tracking-[-0.055em] md:text-7xl">Shaping Minds. Building Futures. Transforming Communities.</h1>
            <p className="mt-8 max-w-2xl text-base leading-8 text-slate-200 md:text-lg">Tima-Ade University is a forward-looking institution in Gabiley, Somaliland, committed to academic excellence, character, innovation, and meaningful contribution to society.</p>
            <div className="mt-10 flex flex-col gap-3 sm:flex-row"><Link href="#who-we-are" className="inline-flex items-center justify-center gap-2 bg-white px-5 py-3 text-sm font-bold text-primary-900 hover:bg-blue-50">Discover Tima-Ade <ArrowDownRight size={17} /></Link><Link href="/about/campuses" className="inline-flex items-center justify-center gap-2 border border-white/45 px-5 py-3 text-sm font-bold text-white hover:bg-white/10">Explore Our Campuses <ArrowRight size={17} /></Link></div>
          </motion.div>
          <div className="mt-20 flex items-center gap-4 text-xs font-semibold uppercase tracking-[0.18em] text-blue-100"><span className="h-px w-12 bg-blue-200" /> Gabiley · Somaliland</div>
        </div>
      </section>

      <section id="who-we-are" className="py-20 md:py-28"><div className="container-xl grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-500">Who we are</p><h2 className="mt-4 text-4xl font-bold leading-tight tracking-[-0.05em] text-slate-950 md:text-5xl">A university with ambition, rooted in place.</h2></div><div className="grid gap-8 md:grid-cols-[1.1fr_0.9fr]"><p className="text-xl leading-9 text-slate-700">Tima-Ade is a learning community for people who want to understand more, contribute more, and become more capable of shaping the future around them.</p><div className="border-l border-slate-300 pl-6 text-sm leading-7 text-slate-600">We bring together academic excellence, innovation, leadership, and character development so that education becomes a lasting contribution to society.</div></div></div></section>

      <section className="bg-slate-950 py-20 text-white md:py-28"><div className="container-xl grid gap-14 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-300">Our story</p><h2 className="mt-4 text-4xl font-bold leading-tight tracking-[-0.05em] md:text-5xl">Built carefully. Moving forward with purpose.</h2><p className="mt-6 max-w-sm leading-7 text-slate-300">Our story is an ongoing commitment to make high-quality education matter in the lives of our students and communities.</p></div><div className="border-l border-white/20 pl-7 md:pl-12">{timeline.map((item, index) => <div key={item.label} className="relative pb-12 last:pb-0"><span className="absolute -left-[31px] top-1 h-3 w-3 rounded-full border-2 border-blue-300 bg-slate-950 md:-left-[55px]" /><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-300">0{index + 1} · {item.label}</p><p className="mt-4 max-w-xl text-lg leading-8 text-slate-200">{item.text}</p></div>)}</div></div></section>

      <section className="py-20 md:py-28"><div className="container-xl grid gap-6 lg:grid-cols-2"><article className="border border-slate-200 bg-white p-8 shadow-card md:p-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-500">Our mission</p><h2 className="mt-5 text-3xl font-bold tracking-[-0.04em] text-slate-950 md:text-4xl">Education that develops capability and serves society.</h2><p className="mt-6 leading-8 text-slate-600">We provide quality education that develops capable graduates, encourages innovation, builds character, and prepares students to contribute responsibly to their communities.</p></article><article className="bg-primary-900 p-8 text-white md:p-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-200">Our vision</p><h2 className="mt-5 text-3xl font-bold tracking-[-0.04em] md:text-4xl">A respected institution known for excellence, innovation, and leadership.</h2><p className="mt-6 leading-8 text-slate-200">Tima-Ade will grow as a trusted center of learning and positive societal impact, recognized for the quality of its graduates and the relevance of its work.</p></article></div></section>

      <section className="border-y border-slate-200 bg-white py-20 md:py-28"><div className="container-xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-500">What guides us</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.05em] text-slate-950 md:text-5xl">Core values</h2></div><p className="max-w-md leading-7 text-slate-600">The standards we bring to our classrooms, partnerships, decisions, and everyday relationships.</p></div><div className="mt-12 grid border-l border-t border-slate-200 sm:grid-cols-2 lg:grid-cols-4">{values.map(({ icon: Icon, title, text }) => <article key={title} className="group border-b border-r border-slate-200 p-6 transition-colors hover:bg-slate-50 md:p-7"><Icon size={23} className="text-primary-500 transition-transform group-hover:-translate-y-1" /><h3 className="mt-10 text-lg font-bold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

      <section className="py-20 md:py-28"><div className="container-xl grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div className="relative min-h-[440px] overflow-hidden bg-slate-200"><Image src="/images/home/community.jpg" alt="Tima-Ade University community" fill sizes="(max-width: 1024px) 100vw, 45vw" className="object-cover" /><div className="absolute inset-x-0 bottom-0 bg-primary-900/90 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-200">Leadership message</p><p className="mt-2 text-sm">Office of the President</p></div></div><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-500">From university leadership</p><blockquote className="mt-5 text-3xl font-semibold leading-tight tracking-[-0.04em] text-slate-950 md:text-5xl">“The future is shaped by the quality of the people we equip to meet it.”</blockquote><p className="mt-7 max-w-xl leading-8 text-slate-600">At Tima-Ade, we believe a university’s deepest contribution is measured in the confidence, competence, and conscience of its graduates. We are committed to building that contribution patiently, together.</p><p className="mt-8 font-serif text-2xl italic text-primary-700">Tima-Ade University</p></div></div></section>

      <section className="bg-slate-100 py-20 md:py-28"><div className="container-xl"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-500">Academic excellence</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.05em] text-slate-950 md:text-5xl">A serious education for a changing world.</h2></div><div><p className="max-w-2xl text-xl leading-9 text-slate-700">We invest in quality teaching, qualified educators, research-minded learning, and modern approaches that keep education relevant to students, industry, and community.</p><div className="mt-10 grid gap-5 border-t border-slate-300 pt-6 sm:grid-cols-3"><div><p className="text-2xl font-bold text-primary-700">01</p><p className="mt-2 text-sm leading-6 text-slate-600">Strong academic foundations</p></div><div><p className="text-2xl font-bold text-primary-700">02</p><p className="mt-2 text-sm leading-6 text-slate-600">Research and innovation mindset</p></div><div><p className="text-2xl font-bold text-primary-700">03</p><p className="mt-2 text-sm leading-6 text-slate-600">Development beyond the classroom</p></div></div></div></div></div></section>

      <section className="py-20 md:py-28"><div className="container-xl grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-500">The student experience</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.05em] text-slate-950 md:text-5xl">More than a place to study.</h2><p className="mt-6 leading-7 text-slate-600">Students find room to learn, lead, experiment, connect, and grow into the people their communities need.</p></div><div className="grid gap-4 sm:grid-cols-2">{experiences.map(({ icon: Icon, title, text }) => <article key={title} className="border border-slate-200 p-6 hover:border-primary-300 hover:shadow-card"><Icon className="text-primary-500" size={24} /><h3 className="mt-8 text-xl font-bold text-slate-950">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div></div></section>

      <section className="bg-primary-50 py-20 md:py-28"><div className="container-xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary-500">The Tima-Ade difference</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.05em] text-slate-950 md:text-5xl">Why Tima-Ade?</h2><div className="mt-12 grid gap-x-10 gap-y-8 md:grid-cols-2 lg:grid-cols-3"><div className="flex gap-4"><Building2 className="shrink-0 text-primary-500" /><div><h3 className="font-bold text-slate-950">Academic excellence</h3><p className="mt-2 text-sm leading-6 text-slate-600">Purposeful study grounded in quality teaching.</p></div></div><div className="flex gap-4"><Users className="shrink-0 text-primary-500" /><div><h3 className="font-bold text-slate-950">Student-centered learning</h3><p className="mt-2 text-sm leading-6 text-slate-600">An environment designed around student growth.</p></div></div><div className="flex gap-4"><FlaskConical className="shrink-0 text-primary-500" /><div><h3 className="font-bold text-slate-950">Innovation and technology</h3><p className="mt-2 text-sm leading-6 text-slate-600">Learning connected to ideas and practical challenges.</p></div></div><div className="flex gap-4"><BookOpen className="shrink-0 text-primary-500" /><div><h3 className="font-bold text-slate-950">Relevant education</h3><p className="mt-2 text-sm leading-6 text-slate-600">Knowledge that speaks to professional and community life.</p></div></div><div className="flex gap-4"><Compass className="shrink-0 text-primary-500" /><div><h3 className="font-bold text-slate-950">Leadership development</h3><p className="mt-2 text-sm leading-6 text-slate-600">Character and judgment built through experience.</p></div></div><div className="flex gap-4"><Globe2 className="shrink-0 text-primary-500" /><div><h3 className="font-bold text-slate-950">Community impact</h3><p className="mt-2 text-sm leading-6 text-slate-600">A university committed to the society around it.</p></div></div></div></div></section>

      <section className="relative overflow-hidden bg-slate-950 py-20 text-white md:py-28"><div className="absolute right-0 top-0 h-full w-1/3 bg-[linear-gradient(135deg,transparent,rgba(56,189,248,0.12))]" /><div className="container-xl relative grid gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-300">Institutional impact</p><h2 className="mt-4 text-4xl font-bold tracking-[-0.05em] md:text-5xl">Knowledge that stays connected to life.</h2></div><div className="grid gap-8 sm:grid-cols-2"><div><p className="text-3xl font-bold text-white">Education</p><p className="mt-3 leading-7 text-slate-300">Expanding the knowledge, confidence, and opportunity available to the next generation.</p></div><div><p className="text-3xl font-bold text-white">Leadership</p><p className="mt-3 leading-7 text-slate-300">Preparing people to take thoughtful responsibility in organizations and communities.</p></div><div><p className="text-3xl font-bold text-white">Innovation</p><p className="mt-3 leading-7 text-slate-300">Encouraging ideas, research, and practical solutions for a changing region.</p></div><div><p className="text-3xl font-bold text-white">Opportunity</p><p className="mt-3 leading-7 text-slate-300">Creating pathways for graduates to contribute to a more capable future.</p></div></div></div></section>

      <section className="bg-primary-900 py-20 text-white md:py-28"><div className="container-xl flex flex-col justify-between gap-10 md:flex-row md:items-end"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-200">Your next chapter</p><h2 className="mt-5 text-4xl font-bold tracking-[-0.05em] md:text-6xl">Discover the Tima-Ade Experience</h2><p className="mt-6 max-w-xl leading-8 text-slate-200">Explore the people, programmes, and places that make Tima-Ade University a meaningful place to begin.</p></div><div className="flex flex-col gap-3 sm:flex-row md:flex-col"><Link href="/academics" className="inline-flex items-center justify-center gap-2 bg-white px-5 py-3 text-sm font-bold text-primary-900 hover:bg-blue-50">Explore Programs <ArrowRight size={17} /></Link><Link href="/about/campuses" className="inline-flex items-center justify-center gap-2 border border-white/40 px-5 py-3 text-sm font-bold text-white hover:bg-white/10">Visit Our Campuses <ArrowRight size={17} /></Link></div></div></section>
    </AboutPage>
  )
}
