@extends('layouts.app')

@section('title', 'Academic Standing')

@section('content')
<div class="container-fluid px-4 py-4 bg-light min-vh-100">
    <div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-3 mb-4"><div><p class="text-uppercase text-muted small fw-semibold mb-1">Registrar workspace</p><h1 class="h2 mb-1">Academic Standing</h1><p class="text-muted mb-0">Automated GPA, credit, and failed-course evaluation from recorded examination marks.</p></div></div>
    <form class="card border-0 shadow-sm mb-4" method="GET"><div class="card-body row g-2 align-items-end"><div class="col-12 col-md-6"><label for="standing-search" class="form-label">Search student</label><input id="standing-search" name="search" value="{{ request('search') }}" class="form-control" placeholder="Name"></div><div class="col-12 col-md-4"><label for="standing-status" class="form-label">Status</label><select id="standing-status" name="status" class="form-select"><option value="">All statuses</option>@foreach(['good' => 'Good standing', 'probation' => 'Academic probation', 'suspended' => 'Suspended', 'dismissed' => 'Dismissed'] as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-12 col-md-2"><button class="btn btn-primary w-100" type="submit">Filter</button></div></div></form>
    <section class="card border-0 shadow-sm" aria-labelledby="standing-heading"><div class="card-header bg-white border-bottom"><h2 id="standing-heading" class="h5 mb-0">Student evaluations</h2></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Student</th><th>GPA</th><th>Credits assessed</th><th>Failed courses</th><th>Status</th><th>Action</th></tr></thead><tbody>@forelse($students as $student)@php($standing = $student->computed_standing)<tr><td>{{ $student->user->name ?? 'Unknown student' }}<span class="d-block small text-muted">{{ $student->student_id }}</span></td><td>{{ number_format($standing['cumulative_gpa'], 2) }}</td><td>{{ $standing['assessed_count'] }}</td><td>{{ $standing['failed_courses'] }}</td><td><span class="badge {{ $standing['status'] === 'good' ? 'text-bg-success' : ($standing['status'] === 'probation' ? 'text-bg-warning' : 'text-bg-danger') }}">{{ $standing['honors'] === 'deans_list' ? "Dean's List" : Str::title($standing['status']) }}</span></td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('registrar.academic-standing.edit', $student) }}">Review</a></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">No student records match this filter.</td></tr>@endforelse</tbody></table></div><div class="p-3">{{ $students->links() }}</div></section>
</div>
@endsection
