@extends('layouts.app')
@php($view = $view ?? 'applications')
@php($titles = ['applications' => 'Admissions Applications', 'applicants' => 'Applicants', 'documents' => 'Admissions Documents', 'reviews' => 'Application Reviews', 'interviews' => 'Interviews', 'decisions' => 'Admission Decisions'])
@section('title', $titles[$view] ?? 'Admissions')
@section('breadcrumb')<li class="breadcrumb-item active">{{ $titles[$view] ?? 'Admissions' }}</li>@endsection
@section('content')
<div class="container-fluid px-0"><div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="page-title mb-1">{{ $titles[$view] ?? 'Admissions' }}</h3><p class="text-muted small mb-0">Real admissions records available to your role.</p></div></div>
@if($view === 'interviews')
	<div class="card custom-card"><div class="card-body py-5 text-center"><i class="bi bi-calendar2-event fs-1 text-muted"></i><h5 class="mt-3">No interview records</h5><p class="text-muted mb-0">Interview scheduling is not currently part of the admissions data model.</p></div></div>
@else
	@if($view === 'documents')
		<div class="row g-3 mb-4">
			@foreach([
				'total' => 'Total Documents',
				'pending_review' => 'Pending Review',
				'verified' => 'Verified',
				'rejected' => 'Rejected',
				'missing' => 'Missing Documents',
			] as $key => $label)
				<div class="col-6 col-lg-2">
					<div class="card custom-card h-100">
						<div class="card-body">
							<span class="text-muted small d-block">{{ $label }}</span>
							<strong class="fs-3 text-dark">{{ $documentStats[$key] ?? 0 }}</strong>
						</div>
					</div>
				</div>
			@endforeach
		</div>
	@else
		<div class="row g-3 mb-4">@foreach(['total' => 'Total Applications', 'submitted' => 'New / Submitted', 'under_review' => 'Under Review', 'documents_pending' => 'Awaiting Documents', 'interviews_pending' => 'Interviews Pending', 'approved' => 'Accepted', 'declined' => 'Rejected'] as $key => $label)<div class="col-6 col-lg-3"><a class="card custom-card h-100 text-decoration-none" href="{{ $key === 'interviews_pending' ? route('admin.interviews') : ($key === 'approved' || $key === 'declined' ? route('admin.decisions', ['status' => $key]) : route('admin.applications', $key === 'total' ? [] : ($key === 'documents_pending' ? ['document_status' => 'submitted'] : ['status' => $key === 'submitted' ? 'submitted' : $key]))) }}"><div class="card-body"><span class="text-muted small d-block">{{ $label }}</span><strong class="fs-3 text-dark">{{ $stats[$key] }}</strong></div></a></div>@endforeach</div>
	@endif
	<div class="card custom-card mb-4"><div class="card-body"><form method="GET" action="{{ $view === 'reviews' ? route('admin.reviews') : route('admin.applications') }}" class="row g-3"><input type="hidden" name="view" value="{{ $view }}"><div class="col-lg-4"><label class="form-label" for="application-search">Search records</label><input id="application-search" type="search" name="search" class="form-control" value="{{ request('search') }}" placeholder="{{ $view === 'documents' ? 'Applicant, reference, document, or file name' : 'Reference, name, email, or phone' }}"></div><div class="col-md-3 col-lg-2"><label class="form-label" for="application-status">Status</label><select id="application-status" name="status" class="form-select"><option value="">All statuses</option>@foreach(['submitted','under_review','approved','declined'] as $status)<option value="{{ $status }}" @selected(request('status') === $status)>{{ ucfirst(str_replace('_', ' ', $status)) }}</option>@endforeach</select></div><div class="col-md-3 col-lg-2"><label class="form-label" for="document-status">Document status</label><select id="document-status" name="document_status" class="form-select"><option value="">All documents</option>@foreach(['submitted' => 'Pending verification', 'verified' => 'Verified', 'requires_correction' => 'Requires correction', 'missing' => 'Missing documents'] as $status => $label)<option value="{{ $status }}" @selected($documentStatus === $status)>{{ $label }}</option>@endforeach</select></div><div class="col-md-3 col-lg-2"><label class="form-label" for="sort-order">Sort</label><select id="sort-order" name="sort" class="form-select"><option value="newest" @selected($sort === 'desc')>Newest first</option><option value="oldest" @selected($sort === 'asc')>Oldest first</option></select></div><div class="col-md-3 col-lg-2"><label class="form-label" for="submitted-from">From</label><input id="submitted-from" type="date" name="submitted_from" class="form-control" value="{{ request('submitted_from') }}"></div><div class="col-md-3 col-lg-2"><label class="form-label" for="submitted-to">To</label><input id="submitted-to" type="date" name="submitted_to" class="form-control" value="{{ request('submitted_to') }}"></div><div class="col-md-3 col-lg-2 d-flex align-items-end"><button class="btn btn-dark w-100" type="submit"><i class="bi bi-funnel me-1"></i> Filter</button></div></form></div></div>
	<div class="card custom-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr>@if($view === 'documents')<th>Document</th><th>Applicant</th><th>Application</th><th>Uploaded</th><th>Status</th><th>Notes</th><th>Action</th>@else<th>Reference</th><th>Applicant</th><th>Program / Grade</th><th>Submitted</th><th>Status</th><th>Documents</th><th>Interview</th><th>Updated</th><th></th>@endif</tr></thead><tbody>@if($view === 'documents')@forelse($applications as $application)@foreach($application->documents ?? [] as $documentIndex => $document)<tr><td class="fw-semibold">{{ $document['name'] ?? 'Submitted document' }}</td><td>{{ $application->name }}<small class="d-block text-muted">{{ $application->email }}</small></td><td>{{ $application->reference }}</td><td>{{ isset($document['uploaded_at']) ? \Carbon\Carbon::parse($document['uploaded_at'])->format('d M Y') : $application->created_at->format('d M Y') }}</td><td><span class="badge text-bg-{{ ($document['status'] ?? 'submitted') === 'verified' ? 'success' : (($document['status'] ?? 'submitted') === 'requires_correction' ? 'danger' : 'warning') }}">{{ ucfirst(str_replace('_', ' ', $document['status'] ?? 'submitted')) }}</span></td><td>{{ $document['verification_notes'] ?? 'None recorded' }}</td><td><a href="{{ route('admin.applications.show', $application) }}#document-status-{{ $documentIndex }}" class="btn btn-sm btn-outline-primary">Review</a></td></tr>@endforeach @empty<tr><td colspan="7" class="text-center text-muted py-5">No admissions documents match the current filters.</td></tr>@endforelse @else @forelse($applications as $application)<tr><td class="fw-bold">{{ $application->reference }}</td><td>{{ $application->name }}<small class="d-block text-muted">{{ $application->email }}<br>{{ $application->phone }}</small></td><td>{{ $application->grade_interested }}</td><td>{{ $application->created_at->format('d M Y') }}</td><td><span class="badge text-bg-{{ $application->status === 'approved' ? 'success' : ($application->status === 'declined' ? 'danger' : ($application->status === 'under_review' ? 'warning' : 'secondary')) }}">{{ ucfirst(str_replace('_', ' ', $application->status)) }}</span></td><td>{{ count($application->documents ?? []) }} submitted</td><td><span class="text-muted small">Not available</span></td><td>{{ $application->updated_at->format('d M Y') }}</td><td><a href="{{ route('admin.applications.show', $application) }}" class="btn btn-sm btn-outline-primary">Open</a></td></tr>@empty<tr><td colspan="9" class="text-center text-muted py-5">No {{ strtolower($titles[$view] ?? 'records') }} match the current filters.</td></tr>@endforelse @endif</tbody></table></div><div class="p-3">{{ $applications->links() }}</div></div>
@endif
</div>
@endsection
