@extends('layouts.app')
@section('title', 'Review Application ' . $application->reference)
@section('breadcrumb')<li class="breadcrumb-item"><a href="{{ route('admin.applications') }}">Applications</a></li><li class="breadcrumb-item active">{{ $application->reference }}</li>@endsection
@section('content')
<div class="container-fluid px-0">
    <div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="page-title mb-1">{{ $application->name }}</h3><p class="text-muted small mb-0">{{ $application->reference }} · {{ ucfirst(str_replace('_', ' ', $application->status)) }}</p></div><div class="d-flex gap-2">@if(in_array($application->status, ['approved', 'declined'], true))<a href="{{ route('admin.applications.decision-letter', $application) }}" class="btn btn-outline-primary"><i class="bi bi-file-earmark-text me-1"></i>Decision letter</a>@endif<a href="{{ route('admin.applications') }}" class="btn btn-outline-secondary">Back</a></div></div>
    <div class="row g-4">
        <div class="col-lg-7"><div class="card custom-card mb-4"><div class="card-body"><h5>Applicant Information</h5><dl class="row mb-0"><dt class="col-sm-4">Email</dt><dd class="col-sm-8">{{ $application->email }}</dd><dt class="col-sm-4">Phone</dt><dd class="col-sm-8">{{ $application->phone }}</dd><dt class="col-sm-4">Grade</dt><dd class="col-sm-8">{{ $application->grade_interested }}</dd><dt class="col-sm-4">Notes</dt><dd class="col-sm-8">{{ $application->message ?: 'Not provided' }}</dd></dl></div></div><div class="card custom-card"><div class="card-body"><h5>Education Information</h5><dl class="row mb-0">@forelse(($application->education ?? []) as $label => $value)<dt class="col-sm-5">{{ str_replace('_', ' ', ucfirst($label)) }}</dt><dd class="col-sm-7">{{ $value ?: 'Not provided' }}</dd>@empty<p class="text-muted mb-0">No education details provided.</p>@endforelse</dl></div></div></div>
        <div class="col-lg-5"><div class="card custom-card mb-4"><div class="card-body"><h5>Documents</h5>@forelse(($application->documents ?? []) as $documentIndex => $document)<div class="border-bottom pb-3 mb-3"><a class="d-block mb-2" href="{{ route('admin.applications.document', [$application, $documentIndex]) }}"><i class="bi bi-download me-1"></i>{{ $document['name'] ?? 'Submitted document' }}</a><span class="badge text-bg-secondary mb-2">{{ ucfirst(str_replace('_', ' ', $document['status'] ?? 'submitted')) }}</span><form method="POST" action="{{ route('admin.applications.documents.update', [$application, $documentIndex]) }}">@csrf @method('PATCH')<label class="form-label small" for="document-status-{{ $documentIndex }}">Verification status</label><select id="document-status-{{ $documentIndex }}" name="status" class="form-select form-select-sm mb-2"><option value="submitted" @selected(($document['status'] ?? 'submitted') === 'submitted')>Pending verification</option><option value="verified" @selected(($document['status'] ?? '') === 'verified')>Verified</option><option value="requires_correction" @selected(($document['status'] ?? '') === 'requires_correction')>Requires correction</option></select><textarea name="verification_notes" class="form-control form-control-sm mb-2" rows="2" placeholder="Verification notes">{{ $document['verification_notes'] ?? '' }}</textarea><button class="btn btn-sm btn-outline-primary" type="submit">Save verification</button></form></div>@empty<p class="text-muted small mb-0">No documents submitted.</p>@endforelse</div></div>
            @if($application->status === 'submitted')<div class="card custom-card mb-3"><div class="card-body"><h5>Start review</h5><form method="POST" action="{{ route('admin.applications.review', $application) }}">@csrf<button class="btn btn-primary" type="submit">Move to Under Review</button></form></div></div>@endif
            @if($application->status !== 'approved')<div class="card custom-card mb-3"><div class="card-body"><h5>Approve application?</h5><form method="POST" action="{{ route('admin.applications.approve', $application) }}">@csrf<button class="btn btn-success" type="submit">Confirm Approval</button></form></div></div>@endif
            @if($application->status !== 'declined')<div class="card custom-card"><div class="card-body"><h5>Decline application</h5><form method="POST" action="{{ route('admin.applications.decline', $application) }}">@csrf<textarea name="decision_reason" class="form-control mb-2" rows="3" required placeholder="Decision reason"></textarea><button class="btn btn-outline-danger" type="submit">Decline Application</button></form></div></div>@endif
        </div>
    </div>
</div>
@endsection
