@extends('layouts.app')
@section('title', 'Course Completion')
@section('content')
<div class="container-fluid py-4">
    @php($section = $completion['section'])
    <div class="mb-4"><span class="eyebrow-label">Course Progress</span><h2 class="dashboard-section-header mb-1">{{ $section->course->name ?? 'Course' }}</h2><p class="text-muted mb-0">{{ $section->code }} · {{ $section->term->name ?? 'Term' }} · {{ $section->term->academicYear->name ?? 'Academic year' }}</p></div>
    <div class="row g-3 mb-4"><div class="col-md-3"><div class="card custom-card"><div class="card-body"><small class="text-muted">Status</small><h4 class="mt-2 text-capitalize">{{ $completion['status'] }}</h4></div></div></div><div class="col-md-3"><div class="card custom-card"><div class="card-body"><small class="text-muted">Progress</small><h4 class="mt-2">{{ $completion['progress'] }}%</h4><div class="progress"><div class="progress-bar" style="width: {{ $completion['progress'] }}%"></div></div></div></div></div><div class="col-md-3"><div class="card custom-card"><div class="card-body"><small class="text-muted">Graded activities</small><h4 class="mt-2">{{ $completion['graded_count'] }}/{{ $completion['assignments']->count() }}</h4></div></div></div><div class="col-md-3"><div class="card custom-card"><div class="card-body"><small class="text-muted">Missing</small><h4 class="mt-2">{{ $completion['missing_count'] }}</h4></div></div></div></div>
    <div class="card custom-card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Activity</th><th>Status</th><th>Score</th><th>Feedback</th></tr></thead><tbody>@forelse($completion['activities'] as $activity) @php($submission = $activity['submission'])<tr><td>{{ $activity['assignment']->title }}</td><td><span class="badge bg-{{ $activity['state'] === 'graded' ? 'success' : ($activity['state'] === 'missing' ? 'light text-muted' : 'warning-subtle text-warning') }}">{{ ucfirst($activity['state']) }}{{ $submission?->is_late ? ' · Late' : '' }}</span></td><td>{{ $submission?->score !== null ? $submission->score.'/'.$activity['assignment']->max_points.' ('.$activity['percentage'].'%)' : '—' }}</td><td>{{ $submission?->feedback ?? '—' }}</td></tr>@empty<tr><td colspan="4" class="text-center py-5 text-muted">No published coursework is attached to this enrolled course yet.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
