@extends('layouts.app')
@section('title', 'Quiz Preview')
@section('content')
<div class="container py-4"><span class="eyebrow-label">Teacher Preview</span><h2 class="dashboard-section-header">{{ $test->title }}</h2><p class="text-muted">{{ $test->instructions }}</p>
@if($test->status === 'draft')
<form method="POST" action="{{ route('teacher.tests.question-pools.store', $test) }}" class="card custom-card mb-4"><div class="card-body row g-3">@csrf<div class="col-md-4"><label class="form-label">Question type</label><select name="question_type" class="form-select"><option value="">Any type</option><option value="multiple_choice">Multiple choice</option><option value="true_false">True / False</option><option value="short_answer">Short answer</option></select></div><div class="col-md-4"><label class="form-label">Questions to draw</label><input type="number" name="questions_count" min="1" class="form-control" required></div><div class="col-md-4"><label class="form-label">Points per question</label><input type="number" name="marks_per_question" min="1" class="form-control"></div><div class="col-12"><button class="btn btn-outline-primary">Add random pool</button></div></div></form>
@endif
@foreach($test->questionPools as $pool)<div class="card custom-card mb-3"><div class="card-body"><strong>Random pool: {{ $pool->questions_count }} {{ $pool->question_type ? str_replace('_', ' ', $pool->question_type) : 'mixed' }} questions</strong><span class="badge bg-light text-dark float-end">{{ $poolPreviews[$pool->id]->count() }} previewed</span>@if($test->status === 'draft')<form method="POST" action="{{ route('teacher.tests.question-pools.destroy', $pool) }}" class="mt-2">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Remove pool</button></form>@endif</div><div class="card-body border-top">@foreach($poolPreviews[$pool->id] as $question)<div class="mb-2">{{ $loop->iteration }}. {{ $question->question_text }} @foreach($question->options as $option) @if($option->is_correct)<span class="badge bg-success">Correct: {{ $option->option_text }}</span>@endif @endforeach</div>@endforeach</div></div>@endforeach
@foreach($test->questions->concat($test->selectedQuestions)->unique('id') as $question)<div class="card custom-card mb-3"><div class="card-body"><strong>{{ $loop->iteration }}. {{ $question->question_text }}</strong><span class="badge bg-light text-dark float-end">{{ $question->pivot->marks ?? $question->marks }} pts</span><ol class="mt-3">@foreach($question->options as $option)<li>{{ $option->option_text }} @if($option->is_correct)<span class="badge bg-success">Correct</span>@endif</li>@endforeach</ol></div></div>@endforeach</div>
@endsection
